import type { ArtworkDefinition } from "../../../theme/artwork/types";

/** screenprint originals; draft until visual review. */
export const ARTWORK_MANIFEST: readonly ArtworkDefinition[] = [
	{
		id: "screenprint-airplane-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/screenprint/airplane-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "screenprint",
		subjectId: "airplane",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "screenprint-airplane",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Bold screenprint using three flat spot-color planes, stencil gaps and coarse ink grain.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:screenprint-airplane-medium-r1:v1:review-20260925",
	},
	{
		id: "screenprint-bag-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/screenprint/bag-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "screenprint",
		subjectId: "bag",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "screenprint-bag",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Bold screenprint using three flat spot-color planes, stencil gaps and coarse ink grain.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:screenprint-bag-medium-r1:v1:review-20260925",
	},
	{
		id: "screenprint-car-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/screenprint/car-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "screenprint",
		subjectId: "car",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "screenprint-car",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Bold screenprint using three flat spot-color planes, stencil gaps and coarse ink grain.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:screenprint-car-medium-r1:v1:review-20260925",
	},
	{
		id: "screenprint-flower-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/screenprint/flower-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "screenprint",
		subjectId: "flower",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "screenprint-flower",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Bold screenprint using three flat spot-color planes, stencil gaps and coarse ink grain.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:screenprint-flower-medium-r1:v1:review-20260925",
	},
	{
		id: "screenprint-grid-panel-panel-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/screenprint/grid-panel-panel.svg",
		format: "svg",
		width: 320,
		height: 240,
		aspect: 1.333333,
		touchId: "screenprint",
		subjectId: "grid-panel",
		role: "panel",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 18,
		maxPrintWidthMm: 128,
		originalityGroupId: "screenprint-grid-panel",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Bold screenprint using three flat spot-color planes, stencil gaps and coarse ink grain.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:screenprint-grid-panel-panel-r1:v1:review-20260925",
	},
	{
		id: "screenprint-heading-band-heading-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/screenprint/heading-band-heading.svg",
		format: "svg",
		width: 320,
		height: 40,
		aspect: 8.0,
		touchId: "screenprint",
		subjectId: "heading-band",
		role: "heading",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 32,
		maxPrintWidthMm: 128,
		originalityGroupId: "screenprint-heading-band",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Bold screenprint using three flat spot-color planes, stencil gaps and coarse ink grain.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:screenprint-heading-band-heading-r1:v1:review-20260925",
	},
	{
		id: "screenprint-leaf-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/screenprint/leaf-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "screenprint",
		subjectId: "leaf",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "screenprint-leaf",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Bold screenprint using three flat spot-color planes, stencil gaps and coarse ink grain.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:screenprint-leaf-medium-r1:v1:review-20260925",
	},
	{
		id: "screenprint-machiya-grid-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/screenprint/machiya-grid-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "screenprint",
		subjectId: "machiya-grid",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "screenprint-machiya-grid",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Bold screenprint using three flat spot-color planes, stencil gaps and coarse ink grain.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:screenprint-machiya-grid-hero-r1:v1:review-20260925",
	},
	{
		id: "screenprint-measurement-rule-rule-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/screenprint/measurement-rule-rule.svg",
		format: "svg",
		width: 320,
		height: 10,
		aspect: 32.0,
		touchId: "screenprint",
		subjectId: "measurement-rule",
		role: "rule",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 24,
		maxPrintWidthMm: 128,
		originalityGroupId: "screenprint-measurement-rule",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Bold screenprint using three flat spot-color planes, stencil gaps and coarse ink grain.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:screenprint-measurement-rule-rule-r1:v1:review-20260925",
	},
	{
		id: "screenprint-mountain-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/screenprint/mountain-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "screenprint",
		subjectId: "mountain",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "screenprint-mountain",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Bold screenprint using three flat spot-color planes, stencil gaps and coarse ink grain.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:screenprint-mountain-hero-r1:v1:review-20260925",
	},
	{
		id: "screenprint-photo-frame-frame-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/screenprint/photo-frame-frame.svg",
		format: "svg",
		width: 320,
		height: 240,
		aspect: 1.333333,
		touchId: "screenprint",
		subjectId: "photo-frame",
		role: "frame",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 18,
		maxPrintWidthMm: 128,
		originalityGroupId: "screenprint-photo-frame",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Bold screenprint using three flat spot-color planes, stencil gaps and coarse ink grain.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:screenprint-photo-frame-frame-r1:v1:review-20260925",
	},
	{
		id: "screenprint-roof-arch-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/screenprint/roof-arch-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "screenprint",
		subjectId: "roof-arch",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "screenprint-roof-arch",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Bold screenprint using three flat spot-color planes, stencil gaps and coarse ink grain.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:screenprint-roof-arch-hero-r1:v1:review-20260925",
	},
	{
		id: "screenprint-route-route-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/screenprint/route-route.svg",
		format: "svg",
		width: 120,
		height: 240,
		aspect: 0.5,
		touchId: "screenprint",
		subjectId: "route",
		role: "route",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 14,
		maxPrintWidthMm: 30,
		originalityGroupId: "screenprint-route",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Bold screenprint using three flat spot-color planes, stencil gaps and coarse ink grain.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:screenprint-route-route-r1:v1:review-20260925",
	},
	{
		id: "screenprint-sea-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/screenprint/sea-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "screenprint",
		subjectId: "sea",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "screenprint-sea",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Bold screenprint using three flat spot-color planes, stencil gaps and coarse ink grain.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:screenprint-sea-hero-r1:v1:review-20260925",
	},
	{
		id: "screenprint-season-pattern-season-pattern-r1",
		revision: 1,
		sourcePath:
			"../../assets/artwork/screenprint/season-pattern-season-pattern.svg",
		format: "svg",
		width: 1000,
		height: 1000,
		aspect: 1.0,
		touchId: "screenprint",
		subjectId: "season-pattern",
		role: "season-pattern",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 30,
		maxPrintWidthMm: 40,
		originalityGroupId: "screenprint-season-pattern",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Bold screenprint using three flat spot-color planes, stencil gaps and coarse ink grain.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId:
			"artwork:screenprint-season-pattern-season-pattern-r1:v1:review-20260925",
		views: [
			{ id: "spring", x: 0, y: 0, width: 500, height: 500 },
			{ id: "summer", x: 500, y: 0, width: 500, height: 500 },
			{ id: "autumn", x: 0, y: 500, width: 500, height: 500 },
			{ id: "winter", x: 500, y: 500, width: 500, height: 500 },
		],
	},
	{
		id: "screenprint-shell-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/screenprint/shell-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "screenprint",
		subjectId: "shell",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "screenprint-shell",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Bold screenprint using three flat spot-color planes, stencil gaps and coarse ink grain.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:screenprint-shell-medium-r1:v1:review-20260925",
	},
	{
		id: "screenprint-sticky-note-tab-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/screenprint/sticky-note-tab.svg",
		format: "svg",
		width: 300,
		height: 100,
		aspect: 3.0,
		touchId: "screenprint",
		subjectId: "sticky-note",
		role: "tab",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 20,
		maxPrintWidthMm: 128,
		originalityGroupId: "screenprint-sticky-note",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Bold screenprint using three flat spot-color planes, stencil gaps and coarse ink grain.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:screenprint-sticky-note-tab-r1:v1:review-20260925",
	},
	{
		id: "screenprint-straight-arrow-straight-arrow-r1",
		revision: 1,
		sourcePath:
			"../../assets/artwork/screenprint/straight-arrow-straight-arrow.svg",
		format: "svg",
		width: 300,
		height: 100,
		aspect: 3.0,
		touchId: "screenprint",
		subjectId: "straight-arrow",
		role: "straight-arrow",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 30,
		originalityGroupId: "screenprint-straight-arrow",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Bold screenprint using three flat spot-color planes, stencil gaps and coarse ink grain.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId:
			"artwork:screenprint-straight-arrow-straight-arrow-r1:v1:review-20260925",
	},
	{
		id: "screenprint-street-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/screenprint/street-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "screenprint",
		subjectId: "street",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "screenprint-street",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Bold screenprint using three flat spot-color planes, stencil gaps and coarse ink grain.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:screenprint-street-hero-r1:v1:review-20260925",
	},
	{
		id: "screenprint-tableware-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/screenprint/tableware-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "screenprint",
		subjectId: "tableware",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "screenprint-tableware",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Bold screenprint using three flat spot-color planes, stencil gaps and coarse ink grain.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:screenprint-tableware-medium-r1:v1:review-20260925",
	},
	{
		id: "screenprint-ticket-label-label-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/screenprint/ticket-label-label.svg",
		format: "svg",
		width: 200,
		height: 100,
		aspect: 2.0,
		touchId: "screenprint",
		subjectId: "ticket-label",
		role: "label",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 14,
		maxPrintWidthMm: 128,
		originalityGroupId: "screenprint-ticket-label",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Bold screenprint using three flat spot-color planes, stencil gaps and coarse ink grain.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:screenprint-ticket-label-label-r1:v1:review-20260925",
	},
	{
		id: "screenprint-train-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/screenprint/train-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "screenprint",
		subjectId: "train",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "screenprint-train",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Bold screenprint using three flat spot-color planes, stencil gaps and coarse ink grain.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:screenprint-train-medium-r1:v1:review-20260925",
	},
	{
		id: "screenprint-turn-arrow-turn-arrow-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/screenprint/turn-arrow-turn-arrow.svg",
		format: "svg",
		width: 300,
		height: 100,
		aspect: 3.0,
		touchId: "screenprint",
		subjectId: "turn-arrow",
		role: "turn-arrow",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 30,
		originalityGroupId: "screenprint-turn-arrow",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Bold screenprint using three flat spot-color planes, stencil gaps and coarse ink grain.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:screenprint-turn-arrow-turn-arrow-r1:v1:review-20260925",
	},
	{
		id: "screenprint-urban-window-railway-hero-r1",
		revision: 1,
		sourcePath:
			"../../assets/artwork/screenprint/urban-window-railway-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "screenprint",
		subjectId: "urban-window-railway",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "screenprint-urban-window-railway",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Bold screenprint using three flat spot-color planes, stencil gaps and coarse ink grain.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId:
			"artwork:screenprint-urban-window-railway-hero-r1:v1:review-20260925",
	},
];
