import type { ArtworkDefinition } from "../../../theme/artwork/types";

/** ink-wash original raster works; draft pending review. */
export const ARTWORK_MANIFEST: readonly ArtworkDefinition[] = [
	{
		id: "ink-wash-mountain-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/ink-wash/mountain-hero.webp",
		format: "webp",
		width: 1536,
		height: 1024,
		aspect: 1.5,
		touchId: "ink-wash",
		subjectId: "mountain",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 26,
		maxPrintWidthMm: 128,
		originalityGroupId: "ink-wash-mountain",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of translucent washes, softened edges and pigment marks; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "ink-wash-sea-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/ink-wash/sea-hero.webp",
		format: "webp",
		width: 1536,
		height: 1024,
		aspect: 1.5,
		touchId: "ink-wash",
		subjectId: "sea",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 26,
		maxPrintWidthMm: 128,
		originalityGroupId: "ink-wash-sea",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of translucent washes, softened edges and pigment marks; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "ink-wash-street-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/ink-wash/street-hero.webp",
		format: "webp",
		width: 1536,
		height: 1024,
		aspect: 1.5,
		touchId: "ink-wash",
		subjectId: "street",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 26,
		maxPrintWidthMm: 128,
		originalityGroupId: "ink-wash-street",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of translucent washes, softened edges and pigment marks; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "ink-wash-machiya-grid-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/ink-wash/machiya-grid-hero.webp",
		format: "webp",
		width: 1536,
		height: 1024,
		aspect: 1.5,
		touchId: "ink-wash",
		subjectId: "machiya-grid",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 26,
		maxPrintWidthMm: 128,
		originalityGroupId: "ink-wash-machiya-grid",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of translucent washes, softened edges and pigment marks; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "ink-wash-urban-window-railway-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/ink-wash/urban-window-railway-hero.webp",
		format: "webp",
		width: 1536,
		height: 1024,
		aspect: 1.5,
		touchId: "ink-wash",
		subjectId: "urban-window-railway",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 26,
		maxPrintWidthMm: 128,
		originalityGroupId: "ink-wash-urban-window-railway",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of translucent washes, softened edges and pigment marks; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "ink-wash-roof-arch-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/ink-wash/roof-arch-hero.webp",
		format: "webp",
		width: 1536,
		height: 1024,
		aspect: 1.5,
		touchId: "ink-wash",
		subjectId: "roof-arch",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 26,
		maxPrintWidthMm: 128,
		originalityGroupId: "ink-wash-roof-arch",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of translucent washes, softened edges and pigment marks; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "ink-wash-train-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/ink-wash/train-medium.webp",
		format: "webp",
		width: 640,
		height: 640,
		aspect: 1.0,
		touchId: "ink-wash",
		subjectId: "train",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "ink-wash-train",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of translucent washes, softened edges and pigment marks; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "ink-wash-airplane-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/ink-wash/airplane-medium.webp",
		format: "webp",
		width: 640,
		height: 640,
		aspect: 1.0,
		touchId: "ink-wash",
		subjectId: "airplane",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "ink-wash-airplane",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of translucent washes, softened edges and pigment marks; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "ink-wash-car-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/ink-wash/car-medium.webp",
		format: "webp",
		width: 640,
		height: 640,
		aspect: 1.0,
		touchId: "ink-wash",
		subjectId: "car",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "ink-wash-car",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of translucent washes, softened edges and pigment marks; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "ink-wash-bag-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/ink-wash/bag-medium.webp",
		format: "webp",
		width: 640,
		height: 640,
		aspect: 1.0,
		touchId: "ink-wash",
		subjectId: "bag",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "ink-wash-bag",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of translucent washes, softened edges and pigment marks; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "ink-wash-tableware-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/ink-wash/tableware-medium.webp",
		format: "webp",
		width: 640,
		height: 640,
		aspect: 1.0,
		touchId: "ink-wash",
		subjectId: "tableware",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "ink-wash-tableware",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of translucent washes, softened edges and pigment marks; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "ink-wash-leaf-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/ink-wash/leaf-medium.webp",
		format: "webp",
		width: 640,
		height: 640,
		aspect: 1.0,
		touchId: "ink-wash",
		subjectId: "leaf",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "ink-wash-leaf",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of translucent washes, softened edges and pigment marks; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "ink-wash-flower-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/ink-wash/flower-medium.webp",
		format: "webp",
		width: 640,
		height: 640,
		aspect: 1.0,
		touchId: "ink-wash",
		subjectId: "flower",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "ink-wash-flower",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of translucent washes, softened edges and pigment marks; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "ink-wash-shell-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/ink-wash/shell-medium.webp",
		format: "webp",
		width: 640,
		height: 640,
		aspect: 1.0,
		touchId: "ink-wash",
		subjectId: "shell",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "ink-wash-shell",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of translucent washes, softened edges and pigment marks; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "ink-wash-photo-frame-frame-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/ink-wash/photo-frame-frame.webp",
		format: "webp",
		width: 1536,
		height: 1152,
		aspect: 1.333333,
		touchId: "ink-wash",
		subjectId: "photo-frame",
		role: "frame",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "ink-wash-photo-frame",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of translucent washes, softened edges and pigment marks; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "ink-wash-heading-band-heading-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/ink-wash/heading-band-heading.webp",
		format: "webp",
		width: 1536,
		height: 192,
		aspect: 8.0,
		touchId: "ink-wash",
		subjectId: "heading-band",
		role: "heading",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 32,
		maxPrintWidthMm: 128,
		originalityGroupId: "ink-wash-heading-band",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of translucent washes, softened edges and pigment marks; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "ink-wash-sticky-note-tab-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/ink-wash/sticky-note-tab.webp",
		format: "webp",
		width: 1536,
		height: 512,
		aspect: 3.0,
		touchId: "ink-wash",
		subjectId: "sticky-note",
		role: "tab",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "ink-wash-sticky-note",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of translucent washes, softened edges and pigment marks; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "ink-wash-ticket-label-label-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/ink-wash/ticket-label-label.webp",
		format: "webp",
		width: 1536,
		height: 768,
		aspect: 2.0,
		touchId: "ink-wash",
		subjectId: "ticket-label",
		role: "label",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 128,
		originalityGroupId: "ink-wash-ticket-label",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of translucent washes, softened edges and pigment marks; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "ink-wash-measurement-rule-rule-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/ink-wash/measurement-rule-rule.webp",
		format: "webp",
		width: 1536,
		height: 48,
		aspect: 32.0,
		touchId: "ink-wash",
		subjectId: "measurement-rule",
		role: "rule",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 28,
		maxPrintWidthMm: 128,
		originalityGroupId: "ink-wash-measurement-rule",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of translucent washes, softened edges and pigment marks; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "ink-wash-grid-panel-panel-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/ink-wash/grid-panel-panel.webp",
		format: "webp",
		width: 1536,
		height: 1152,
		aspect: 1.333333,
		touchId: "ink-wash",
		subjectId: "grid-panel",
		role: "panel",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "ink-wash-grid-panel",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of translucent washes, softened edges and pigment marks; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "ink-wash-straight-arrow-straight-arrow-r1",
		revision: 1,
		sourcePath:
			"../../assets/artwork/ink-wash/straight-arrow-straight-arrow.webp",
		format: "webp",
		width: 900,
		height: 300,
		aspect: 3.0,
		touchId: "ink-wash",
		subjectId: "straight-arrow",
		role: "straight-arrow",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 30,
		originalityGroupId: "ink-wash-straight-arrow",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of translucent washes, softened edges and pigment marks; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "ink-wash-turn-arrow-turn-arrow-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/ink-wash/turn-arrow-turn-arrow.webp",
		format: "webp",
		width: 900,
		height: 300,
		aspect: 3.0,
		touchId: "ink-wash",
		subjectId: "turn-arrow",
		role: "turn-arrow",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 30,
		originalityGroupId: "ink-wash-turn-arrow",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of translucent washes, softened edges and pigment marks; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "ink-wash-route-route-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/ink-wash/route-route.webp",
		format: "webp",
		width: 600,
		height: 1200,
		aspect: 0.5,
		touchId: "ink-wash",
		subjectId: "route",
		role: "route",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 14,
		maxPrintWidthMm: 30,
		originalityGroupId: "ink-wash-route",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of translucent washes, softened edges and pigment marks; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "ink-wash-season-pattern-season-pattern-r1",
		revision: 1,
		sourcePath:
			"../../assets/artwork/ink-wash/season-pattern-season-pattern.webp",
		format: "webp",
		width: 1000,
		height: 1000,
		aspect: 1.0,
		touchId: "ink-wash",
		subjectId: "season-pattern",
		role: "season-pattern",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 36,
		maxPrintWidthMm: 40,
		originalityGroupId: "ink-wash-season-pattern",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of translucent washes, softened edges and pigment marks; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
		views: [
			{ id: "spring", x: 0, y: 0, width: 500, height: 500 },
			{ id: "summer", x: 500, y: 0, width: 500, height: 500 },
			{ id: "autumn", x: 0, y: 500, width: 500, height: 500 },
			{ id: "winter", x: 500, y: 500, width: 500, height: 500 },
		],
	},
];
