import type { ArtworkDefinition } from "../../../theme/artwork/types";

/** engraving originals; draft until visual review. */
export const ARTWORK_MANIFEST: readonly ArtworkDefinition[] = [
	{
		id: "engraving-airplane-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/engraving/airplane-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "engraving",
		subjectId: "airplane",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "engraving-airplane",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original engraving treatment with fine contour strokes and dense parallel and crossing hatch fields for tonal depth.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "engraving-bag-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/engraving/bag-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "engraving",
		subjectId: "bag",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "engraving-bag",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original engraving treatment with fine contour strokes and dense parallel and crossing hatch fields for tonal depth.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "engraving-car-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/engraving/car-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "engraving",
		subjectId: "car",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "engraving-car",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original engraving treatment with fine contour strokes and dense parallel and crossing hatch fields for tonal depth.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "engraving-flower-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/engraving/flower-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "engraving",
		subjectId: "flower",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "engraving-flower",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original engraving treatment with fine contour strokes and dense parallel and crossing hatch fields for tonal depth.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "engraving-grid-panel-panel-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/engraving/grid-panel-panel.svg",
		format: "svg",
		width: 320,
		height: 240,
		aspect: 1.333333,
		touchId: "engraving",
		subjectId: "grid-panel",
		role: "panel",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 18,
		maxPrintWidthMm: 128,
		originalityGroupId: "engraving-grid-panel",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original engraving treatment with fine contour strokes and dense parallel and crossing hatch fields for tonal depth.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "engraving-heading-band-heading-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/engraving/heading-band-heading.svg",
		format: "svg",
		width: 320,
		height: 40,
		aspect: 8.0,
		touchId: "engraving",
		subjectId: "heading-band",
		role: "heading",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 32,
		maxPrintWidthMm: 128,
		originalityGroupId: "engraving-heading-band",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original engraving treatment with fine contour strokes and dense parallel and crossing hatch fields for tonal depth.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "engraving-leaf-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/engraving/leaf-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "engraving",
		subjectId: "leaf",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "engraving-leaf",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original engraving treatment with fine contour strokes and dense parallel and crossing hatch fields for tonal depth.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "engraving-machiya-grid-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/engraving/machiya-grid-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "engraving",
		subjectId: "machiya-grid",
		role: "hero",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "engraving-machiya-grid",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Hand-composed subject-specific vector geometry with fine parallel and cross-hatched shading strokes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "engraving-measurement-rule-rule-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/engraving/measurement-rule-rule.svg",
		format: "svg",
		width: 320,
		height: 10,
		aspect: 32.0,
		touchId: "engraving",
		subjectId: "measurement-rule",
		role: "rule",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 24,
		maxPrintWidthMm: 128,
		originalityGroupId: "engraving-measurement-rule",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original engraving treatment with fine contour strokes and dense parallel and crossing hatch fields for tonal depth.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "engraving-mountain-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/engraving/mountain-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "engraving",
		subjectId: "mountain",
		role: "hero",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "engraving-mountain",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Hand-composed subject-specific vector geometry with fine parallel and cross-hatched shading strokes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "engraving-photo-frame-frame-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/engraving/photo-frame-frame.svg",
		format: "svg",
		width: 320,
		height: 240,
		aspect: 1.333333,
		touchId: "engraving",
		subjectId: "photo-frame",
		role: "frame",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 18,
		maxPrintWidthMm: 128,
		originalityGroupId: "engraving-photo-frame",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original engraving treatment with fine contour strokes and dense parallel and crossing hatch fields for tonal depth.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "engraving-roof-arch-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/engraving/roof-arch-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "engraving",
		subjectId: "roof-arch",
		role: "hero",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "engraving-roof-arch",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Hand-composed subject-specific vector geometry with fine parallel and cross-hatched shading strokes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "engraving-route-route-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/engraving/route-route.svg",
		format: "svg",
		width: 120,
		height: 240,
		aspect: 0.5,
		touchId: "engraving",
		subjectId: "route",
		role: "route",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 14,
		maxPrintWidthMm: 30,
		originalityGroupId: "engraving-route",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original engraving treatment with fine contour strokes and dense parallel and crossing hatch fields for tonal depth.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "engraving-sea-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/engraving/sea-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "engraving",
		subjectId: "sea",
		role: "hero",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "engraving-sea",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Hand-composed subject-specific vector geometry with fine parallel and cross-hatched shading strokes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "engraving-season-pattern-season-pattern-r1",
		revision: 1,
		sourcePath:
			"../../assets/artwork/engraving/season-pattern-season-pattern.svg",
		format: "svg",
		width: 1000,
		height: 1000,
		aspect: 1.0,
		touchId: "engraving",
		subjectId: "season-pattern",
		role: "season-pattern",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 30,
		maxPrintWidthMm: 40,
		originalityGroupId: "engraving-season-pattern",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original engraving treatment with fine contour strokes and dense parallel and crossing hatch fields for tonal depth.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
		views: [
			{ id: "spring", x: 0, y: 0, width: 500, height: 500 },
			{ id: "summer", x: 500, y: 0, width: 500, height: 500 },
			{ id: "autumn", x: 0, y: 500, width: 500, height: 500 },
			{ id: "winter", x: 500, y: 500, width: 500, height: 500 },
		],
	},
	{
		id: "engraving-shell-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/engraving/shell-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "engraving",
		subjectId: "shell",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "engraving-shell",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original engraving treatment with fine contour strokes and dense parallel and crossing hatch fields for tonal depth.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "engraving-sticky-note-tab-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/engraving/sticky-note-tab.svg",
		format: "svg",
		width: 300,
		height: 100,
		aspect: 3.0,
		touchId: "engraving",
		subjectId: "sticky-note",
		role: "tab",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 20,
		maxPrintWidthMm: 128,
		originalityGroupId: "engraving-sticky-note",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original engraving treatment with fine contour strokes and dense parallel and crossing hatch fields for tonal depth.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "engraving-straight-arrow-straight-arrow-r1",
		revision: 1,
		sourcePath:
			"../../assets/artwork/engraving/straight-arrow-straight-arrow.svg",
		format: "svg",
		width: 300,
		height: 100,
		aspect: 3.0,
		touchId: "engraving",
		subjectId: "straight-arrow",
		role: "straight-arrow",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 30,
		originalityGroupId: "engraving-straight-arrow",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original engraving treatment with fine contour strokes and dense parallel and crossing hatch fields for tonal depth.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "engraving-street-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/engraving/street-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "engraving",
		subjectId: "street",
		role: "hero",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "engraving-street",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Hand-composed subject-specific vector geometry with fine parallel and cross-hatched shading strokes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "engraving-tableware-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/engraving/tableware-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "engraving",
		subjectId: "tableware",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "engraving-tableware",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original engraving treatment with fine contour strokes and dense parallel and crossing hatch fields for tonal depth.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "engraving-ticket-label-label-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/engraving/ticket-label-label.svg",
		format: "svg",
		width: 200,
		height: 100,
		aspect: 2.0,
		touchId: "engraving",
		subjectId: "ticket-label",
		role: "label",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 14,
		maxPrintWidthMm: 128,
		originalityGroupId: "engraving-ticket-label",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original engraving treatment with fine contour strokes and dense parallel and crossing hatch fields for tonal depth.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "engraving-train-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/engraving/train-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "engraving",
		subjectId: "train",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "engraving-train",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original engraving treatment with fine contour strokes and dense parallel and crossing hatch fields for tonal depth.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "engraving-turn-arrow-turn-arrow-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/engraving/turn-arrow-turn-arrow.svg",
		format: "svg",
		width: 300,
		height: 100,
		aspect: 3.0,
		touchId: "engraving",
		subjectId: "turn-arrow",
		role: "turn-arrow",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 30,
		originalityGroupId: "engraving-turn-arrow",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original engraving treatment with fine contour strokes and dense parallel and crossing hatch fields for tonal depth.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "engraving-urban-window-railway-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/engraving/urban-window-railway-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "engraving",
		subjectId: "urban-window-railway",
		role: "hero",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "engraving-urban-window-railway",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Hand-composed subject-specific vector geometry with fine parallel and cross-hatched shading strokes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
];
