import type { ArtworkDefinition } from "../../../theme/artwork/types";

/** Technical line art; drafts until visual review. */
export const ARTWORK_MANIFEST: readonly ArtworkDefinition[] = [
	{
		id: "technical-mountain-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/technical/mountain-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "technical",
		subjectId: "mountain",
		role: "hero",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 8,
		maxPrintWidthMm: 128,
		originalityGroupId: "technical-mountain",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Hand-composed subject-specific vector geometry with dimension rails, extension lines, and drafting ticks.",
			licenseEvidence:
				"Original internal artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:technical-mountain-hero-r1:v1:review-20260925",
	},
	{
		id: "technical-sea-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/technical/sea-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "technical",
		subjectId: "sea",
		role: "hero",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 8,
		maxPrintWidthMm: 128,
		originalityGroupId: "technical-sea",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Hand-composed subject-specific vector geometry with dimension rails, extension lines, and drafting ticks.",
			licenseEvidence:
				"Original internal artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:technical-sea-hero-r1:v1:review-20260925",
	},
	{
		id: "technical-street-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/technical/street-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "technical",
		subjectId: "street",
		role: "hero",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 8,
		maxPrintWidthMm: 128,
		originalityGroupId: "technical-street",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Hand-composed subject-specific vector geometry with dimension rails, extension lines, and drafting ticks.",
			licenseEvidence:
				"Original internal artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:technical-street-hero-r1:v1:review-20260925",
	},
	{
		id: "technical-machiya-grid-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/technical/machiya-grid-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "technical",
		subjectId: "machiya-grid",
		role: "hero",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 8,
		maxPrintWidthMm: 128,
		originalityGroupId: "technical-machiya-grid",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Hand-composed subject-specific vector geometry with dimension rails, extension lines, and drafting ticks.",
			licenseEvidence:
				"Original internal artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:technical-machiya-grid-hero-r1:v1:review-20260925",
	},
	{
		id: "technical-urban-window-railway-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/technical/urban-window-railway-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "technical",
		subjectId: "urban-window-railway",
		role: "hero",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 8,
		maxPrintWidthMm: 128,
		originalityGroupId: "technical-urban-window-railway",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Hand-composed subject-specific vector geometry with dimension rails, extension lines, and drafting ticks.",
			licenseEvidence:
				"Original internal artwork authored for this repository; no external source material.",
		},
		reviewId:
			"artwork:technical-urban-window-railway-hero-r1:v1:review-20260925",
	},
	{
		id: "technical-roof-arch-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/technical/roof-arch-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "technical",
		subjectId: "roof-arch",
		role: "hero",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 8,
		maxPrintWidthMm: 128,
		originalityGroupId: "technical-roof-arch",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Hand-composed subject-specific vector geometry with dimension rails, extension lines, and drafting ticks.",
			licenseEvidence:
				"Original internal artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:technical-roof-arch-hero-r1:v1:review-20260925",
	},
	{
		id: "technical-train-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/technical/train-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "technical",
		subjectId: "train",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 8,
		maxPrintWidthMm: 42,
		originalityGroupId: "technical-train",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Individually authored technical line illustration with subject-specific geometry and drafting marks.",
			licenseEvidence:
				"Original internal artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:technical-train-medium-r1:v1:review-20260925",
	},
	{
		id: "technical-airplane-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/technical/airplane-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "technical",
		subjectId: "airplane",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 8,
		maxPrintWidthMm: 42,
		originalityGroupId: "technical-airplane",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Individually authored technical line illustration with subject-specific geometry and drafting marks.",
			licenseEvidence:
				"Original internal artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:technical-airplane-medium-r1:v1:review-20260925",
	},
	{
		id: "technical-car-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/technical/car-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "technical",
		subjectId: "car",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 8,
		maxPrintWidthMm: 42,
		originalityGroupId: "technical-car",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Individually authored technical line illustration with subject-specific geometry and drafting marks.",
			licenseEvidence:
				"Original internal artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:technical-car-medium-r1:v1:review-20260925",
	},
	{
		id: "technical-bag-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/technical/bag-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "technical",
		subjectId: "bag",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 8,
		maxPrintWidthMm: 42,
		originalityGroupId: "technical-bag",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Individually authored technical line illustration with subject-specific geometry and drafting marks.",
			licenseEvidence:
				"Original internal artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:technical-bag-medium-r1:v1:review-20260925",
	},
	{
		id: "technical-tableware-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/technical/tableware-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "technical",
		subjectId: "tableware",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 8,
		maxPrintWidthMm: 42,
		originalityGroupId: "technical-tableware",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Individually authored technical line illustration with subject-specific geometry and drafting marks.",
			licenseEvidence:
				"Original internal artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:technical-tableware-medium-r1:v1:review-20260925",
	},
	{
		id: "technical-leaf-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/technical/leaf-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "technical",
		subjectId: "leaf",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 8,
		maxPrintWidthMm: 42,
		originalityGroupId: "technical-leaf",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Individually authored technical line illustration with subject-specific geometry and drafting marks.",
			licenseEvidence:
				"Original internal artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:technical-leaf-medium-r1:v1:review-20260925",
	},
	{
		id: "technical-flower-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/technical/flower-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "technical",
		subjectId: "flower",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 8,
		maxPrintWidthMm: 42,
		originalityGroupId: "technical-flower",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Individually authored technical line illustration with subject-specific geometry and drafting marks.",
			licenseEvidence:
				"Original internal artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:technical-flower-medium-r1:v1:review-20260925",
	},
	{
		id: "technical-shell-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/technical/shell-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "technical",
		subjectId: "shell",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 8,
		maxPrintWidthMm: 42,
		originalityGroupId: "technical-shell",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Individually authored technical line illustration with subject-specific geometry and drafting marks.",
			licenseEvidence:
				"Original internal artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:technical-shell-medium-r1:v1:review-20260925",
	},
	{
		id: "technical-photo-frame-frame-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/technical/photo-frame-frame.svg",
		format: "svg",
		width: 320,
		height: 240,
		aspect: 1.333333,
		touchId: "technical",
		subjectId: "photo-frame",
		role: "frame",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 8,
		maxPrintWidthMm: 128,
		originalityGroupId: "technical-photo-frame",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Individually authored technical line illustration with subject-specific geometry and drafting marks.",
			licenseEvidence:
				"Original internal artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:technical-photo-frame-frame-r1:v1:review-20260925",
	},
	{
		id: "technical-heading-band-heading-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/technical/heading-band-heading.svg",
		format: "svg",
		width: 320,
		height: 40,
		aspect: 8.0,
		touchId: "technical",
		subjectId: "heading-band",
		role: "heading",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 8,
		maxPrintWidthMm: 128,
		originalityGroupId: "technical-heading-band",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Individually authored technical line illustration with subject-specific geometry and drafting marks.",
			licenseEvidence:
				"Original internal artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:technical-heading-band-heading-r1:v1:review-20260925",
	},
	{
		id: "technical-sticky-note-tab-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/technical/sticky-note-tab.svg",
		format: "svg",
		width: 300,
		height: 100,
		aspect: 3.0,
		touchId: "technical",
		subjectId: "sticky-note",
		role: "tab",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 8,
		maxPrintWidthMm: 128,
		originalityGroupId: "technical-sticky-note",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Individually authored technical line illustration with subject-specific geometry and drafting marks.",
			licenseEvidence:
				"Original internal artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:technical-sticky-note-tab-r1:v1:review-20260925",
	},
	{
		id: "technical-ticket-label-label-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/technical/ticket-label-label.svg",
		format: "svg",
		width: 200,
		height: 100,
		aspect: 2.0,
		touchId: "technical",
		subjectId: "ticket-label",
		role: "label",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 8,
		maxPrintWidthMm: 128,
		originalityGroupId: "technical-ticket-label",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Individually authored technical line illustration with subject-specific geometry and drafting marks.",
			licenseEvidence:
				"Original internal artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:technical-ticket-label-label-r1:v1:review-20260925",
	},
	{
		id: "technical-measurement-rule-rule-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/technical/measurement-rule-rule.svg",
		format: "svg",
		width: 320,
		height: 10,
		aspect: 32.0,
		touchId: "technical",
		subjectId: "measurement-rule",
		role: "rule",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 8,
		maxPrintWidthMm: 128,
		originalityGroupId: "technical-measurement-rule",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Individually authored technical line illustration with subject-specific geometry and drafting marks.",
			licenseEvidence:
				"Original internal artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:technical-measurement-rule-rule-r1:v1:review-20260925",
	},
	{
		id: "technical-grid-panel-panel-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/technical/grid-panel-panel.svg",
		format: "svg",
		width: 320,
		height: 240,
		aspect: 1.333333,
		touchId: "technical",
		subjectId: "grid-panel",
		role: "panel",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 8,
		maxPrintWidthMm: 128,
		originalityGroupId: "technical-grid-panel",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Individually authored technical line illustration with subject-specific geometry and drafting marks.",
			licenseEvidence:
				"Original internal artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:technical-grid-panel-panel-r1:v1:review-20260925",
	},
	{
		id: "technical-straight-arrow-straight-arrow-r1",
		revision: 1,
		sourcePath:
			"../../assets/artwork/technical/straight-arrow-straight-arrow.svg",
		format: "svg",
		width: 300,
		height: 100,
		aspect: 3.0,
		touchId: "technical",
		subjectId: "straight-arrow",
		role: "straight-arrow",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 8,
		maxPrintWidthMm: 30,
		originalityGroupId: "technical-straight-arrow",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Individually authored technical line illustration with subject-specific geometry and drafting marks.",
			licenseEvidence:
				"Original internal artwork authored for this repository; no external source material.",
		},
		reviewId:
			"artwork:technical-straight-arrow-straight-arrow-r1:v1:review-20260925",
	},
	{
		id: "technical-turn-arrow-turn-arrow-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/technical/turn-arrow-turn-arrow.svg",
		format: "svg",
		width: 300,
		height: 100,
		aspect: 3.0,
		touchId: "technical",
		subjectId: "turn-arrow",
		role: "turn-arrow",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 8,
		maxPrintWidthMm: 30,
		originalityGroupId: "technical-turn-arrow",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Individually authored technical line illustration with subject-specific geometry and drafting marks.",
			licenseEvidence:
				"Original internal artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:technical-turn-arrow-turn-arrow-r1:v1:review-20260925",
	},
	{
		id: "technical-route-route-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/technical/route-route.svg",
		format: "svg",
		width: 120,
		height: 240,
		aspect: 0.5,
		touchId: "technical",
		subjectId: "route",
		role: "route",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 8,
		maxPrintWidthMm: 30,
		originalityGroupId: "technical-route",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Individually authored technical line illustration with subject-specific geometry and drafting marks.",
			licenseEvidence:
				"Original internal artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:technical-route-route-r1:v1:review-20260925",
	},
	{
		id: "technical-season-pattern-season-pattern-r1",
		revision: 1,
		sourcePath:
			"../../assets/artwork/technical/season-pattern-season-pattern.svg",
		format: "svg",
		width: 1000,
		height: 1000,
		aspect: 1.0,
		touchId: "technical",
		subjectId: "season-pattern",
		role: "season-pattern",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 8,
		maxPrintWidthMm: 40,
		originalityGroupId: "technical-season-pattern",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Individually authored technical line illustration with subject-specific geometry and drafting marks.",
			licenseEvidence:
				"Original internal artwork authored for this repository; no external source material.",
		},
		reviewId:
			"artwork:technical-season-pattern-season-pattern-r1:v1:review-20260925",
		views: [
			{ id: "spring", x: 0, y: 0, width: 500, height: 500 },
			{ id: "summer", x: 500, y: 0, width: 500, height: 500 },
			{ id: "autumn", x: 0, y: 500, width: 500, height: 500 },
			{ id: "winter", x: 500, y: 500, width: 500, height: 500 },
		],
	},
];
