import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import ts from "typescript";

function literal(object, name, file) {
	const property = object.properties.find(
		(item) =>
			ts.isPropertyAssignment(item) &&
			(item.name?.getText() === name || item.name?.getText() === `"${name}"`),
	);
	if (!property || !ts.isStringLiteral(property.initializer))
		throw new Error(`${file}: ${name}は文字列リテラルで指定してください。`);
	return property.initializer.text;
}

function manifestEntries(file) {
	const source = ts.createSourceFile(
		file,
		readFileSync(file, "utf8"),
		ts.ScriptTarget.Latest,
		true,
	);
	const declaration = source.statements
		.filter(ts.isVariableStatement)
		.flatMap((statement) => [...statement.declarationList.declarations])
		.find((item) => item.name.getText(source) === "ARTWORK_MANIFEST");
	if (!declaration || !ts.isArrayLiteralExpression(declaration.initializer))
		throw new Error(`${file}: ARTWORK_MANIFESTが配列ではありません。`);
	return declaration.initializer.elements.map((item) => {
		if (!ts.isObjectLiteralExpression(item))
			throw new Error(`${file}: 素材定義がオブジェクトではありません。`);
		return {
			id: literal(item, "id", file),
			sourcePath: literal(item, "sourcePath", file),
		};
	});
}

export function generatePublishedArtworkUrls(webRoot) {
	const artworkRoot = join(webRoot, "src/assets/artwork");
	const output = join(webRoot, "src/theme/artwork/publishedUrls.ts");
	const reviews = JSON.parse(
		readFileSync(join(webRoot, "src/theme/reviews/artwork.json"), "utf8"),
	);
	const entries = new Map();
	for (const folder of readdirSync(artworkRoot, { withFileTypes: true })) {
		if (!folder.isDirectory()) continue;
		const file = join(artworkRoot, folder.name, "manifest.ts");
		if (!existsSync(file)) continue;
		for (const entry of manifestEntries(file)) {
			if (entries.has(entry.id))
				throw new Error(`素材IDが重複しています: ${entry.id}`);
			if (
				!/^\.\.\/\.\.\/assets\/artwork\/[a-z-]+\/[a-z0-9-]+\.(svg|webp)$/.test(
					entry.sourcePath,
				) ||
				!existsSync(resolve(dirname(output), entry.sourcePath))
			)
				throw new Error(`素材ファイルが不正です: ${entry.id}`);
			entries.set(entry.id, entry.sourcePath);
		}
	}
	if (!Array.isArray(reviews))
		throw new Error("artwork.jsonは配列が必要です。");
	const activePaths = [];
	const seen = new Set();
	for (const review of reviews) {
		if (review.status !== "active") continue;
		if (seen.has(review.id))
			throw new Error(`active素材IDが重複しています: ${review.id}`);
		seen.add(review.id);
		const sourcePath = entries.get(review.id);
		if (!sourcePath)
			throw new Error(`active素材がmanifestにありません: ${review.id}`);
		activePaths.push(sourcePath);
	}
	activePaths.sort();
	const imports = activePaths.map(
		(path, index) =>
			`import published${index} from ${JSON.stringify(`${path}?url`)};`,
	);
	const properties = activePaths.map((path, index) => {
		const key = JSON.stringify(path);
		const value = `published${index},`;
		return key.length + value.length + 6 <= 80
			? `\t\t${key}: ${value}`
			: `\t\t${key}:\n\t\t\t${value}`;
	});
	const content = [
		"/** Generated by scripts/generatePublishedArtworkUrls.mjs; only active art enters the product bundle. */",
		...imports,
		...(imports.length > 0 ? [""] : []),
		"export const PUBLISHED_ARTWORK_URLS: Readonly<Record<string, string>> =",
		...(properties.length === 0
			? ["\tObject.freeze({});"]
			: ["\tObject.freeze({", ...properties, "\t});"]),
		"",
	].join("\n");
	if (!existsSync(output) || readFileSync(output, "utf8") !== content)
		writeFileSync(output, content);
	return content;
}

if (
	process.argv[1] &&
	import.meta.url === pathToFileURL(resolve(process.argv[1])).href
)
	generatePublishedArtworkUrls(
		resolve(dirname(fileURLToPath(import.meta.url)), ".."),
	);
