import type { ArtworkDefinition } from "../../../theme/artwork/types";

/** gouache original raster works; draft pending review. */
export const ARTWORK_MANIFEST: readonly ArtworkDefinition[] = [
	{
		id: "gouache-mountain-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/gouache/mountain-hero.webp",
		format: "webp",
		width: 1536,
		height: 1024,
		aspect: 1.5,
		touchId: "gouache",
		subjectId: "mountain",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 26,
		maxPrintWidthMm: 128,
		originalityGroupId: "gouache-mountain",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of opaque color planes, underpainting and brush-mark primitives; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:gouache-mountain-hero-r1:v1:review-20260925",
		hasAlpha: false,
	},
	{
		id: "gouache-sea-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/gouache/sea-hero.webp",
		format: "webp",
		width: 1536,
		height: 1024,
		aspect: 1.5,
		touchId: "gouache",
		subjectId: "sea",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 26,
		maxPrintWidthMm: 128,
		originalityGroupId: "gouache-sea",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of opaque color planes, underpainting and brush-mark primitives; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:gouache-sea-hero-r1:v1:review-20260925",
		hasAlpha: false,
	},
	{
		id: "gouache-street-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/gouache/street-hero.webp",
		format: "webp",
		width: 1536,
		height: 1024,
		aspect: 1.5,
		touchId: "gouache",
		subjectId: "street",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 26,
		maxPrintWidthMm: 128,
		originalityGroupId: "gouache-street",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of opaque color planes, underpainting and brush-mark primitives; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:gouache-street-hero-r1:v1:review-20260925",
		hasAlpha: false,
	},
	{
		id: "gouache-machiya-grid-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/gouache/machiya-grid-hero.webp",
		format: "webp",
		width: 1536,
		height: 1024,
		aspect: 1.5,
		touchId: "gouache",
		subjectId: "machiya-grid",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 26,
		maxPrintWidthMm: 128,
		originalityGroupId: "gouache-machiya-grid",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of opaque color planes, underpainting and brush-mark primitives; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:gouache-machiya-grid-hero-r1:v1:review-20260925",
		hasAlpha: false,
	},
	{
		id: "gouache-urban-window-railway-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/gouache/urban-window-railway-hero.webp",
		format: "webp",
		width: 1536,
		height: 1024,
		aspect: 1.5,
		touchId: "gouache",
		subjectId: "urban-window-railway",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 26,
		maxPrintWidthMm: 128,
		originalityGroupId: "gouache-urban-window-railway",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of opaque color planes, underpainting and brush-mark primitives; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:gouache-urban-window-railway-hero-r1:v1:review-20260925",
		hasAlpha: false,
	},
	{
		id: "gouache-roof-arch-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/gouache/roof-arch-hero.webp",
		format: "webp",
		width: 1536,
		height: 1024,
		aspect: 1.5,
		touchId: "gouache",
		subjectId: "roof-arch",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 26,
		maxPrintWidthMm: 128,
		originalityGroupId: "gouache-roof-arch",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of opaque color planes, underpainting and brush-mark primitives; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:gouache-roof-arch-hero-r1:v1:review-20260925",
		hasAlpha: false,
	},
	{
		id: "gouache-train-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/gouache/train-medium.webp",
		format: "webp",
		width: 640,
		height: 640,
		aspect: 1.0,
		touchId: "gouache",
		subjectId: "train",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "gouache-train",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of opaque color planes, underpainting and brush-mark primitives; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:gouache-train-medium-r1:v1:review-20260925",
		hasAlpha: false,
	},
	{
		id: "gouache-airplane-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/gouache/airplane-medium.webp",
		format: "webp",
		width: 640,
		height: 640,
		aspect: 1.0,
		touchId: "gouache",
		subjectId: "airplane",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "gouache-airplane",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of opaque color planes, underpainting and brush-mark primitives; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:gouache-airplane-medium-r1:v1:review-20260925",
		hasAlpha: false,
	},
	{
		id: "gouache-car-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/gouache/car-medium.webp",
		format: "webp",
		width: 640,
		height: 640,
		aspect: 1.0,
		touchId: "gouache",
		subjectId: "car",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "gouache-car",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of opaque color planes, underpainting and brush-mark primitives; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:gouache-car-medium-r1:v1:review-20260925",
		hasAlpha: false,
	},
	{
		id: "gouache-bag-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/gouache/bag-medium.webp",
		format: "webp",
		width: 640,
		height: 640,
		aspect: 1.0,
		touchId: "gouache",
		subjectId: "bag",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "gouache-bag",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of opaque color planes, underpainting and brush-mark primitives; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:gouache-bag-medium-r1:v1:review-20260925",
		hasAlpha: false,
	},
	{
		id: "gouache-tableware-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/gouache/tableware-medium.webp",
		format: "webp",
		width: 640,
		height: 640,
		aspect: 1.0,
		touchId: "gouache",
		subjectId: "tableware",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "gouache-tableware",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of opaque color planes, underpainting and brush-mark primitives; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:gouache-tableware-medium-r1:v1:review-20260925",
		hasAlpha: false,
	},
	{
		id: "gouache-leaf-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/gouache/leaf-medium.webp",
		format: "webp",
		width: 640,
		height: 640,
		aspect: 1.0,
		touchId: "gouache",
		subjectId: "leaf",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "gouache-leaf",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of opaque color planes, underpainting and brush-mark primitives; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:gouache-leaf-medium-r1:v1:review-20260925",
		hasAlpha: false,
	},
	{
		id: "gouache-flower-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/gouache/flower-medium.webp",
		format: "webp",
		width: 640,
		height: 640,
		aspect: 1.0,
		touchId: "gouache",
		subjectId: "flower",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "gouache-flower",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of opaque color planes, underpainting and brush-mark primitives; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:gouache-flower-medium-r1:v1:review-20260925",
		hasAlpha: false,
	},
	{
		id: "gouache-shell-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/gouache/shell-medium.webp",
		format: "webp",
		width: 640,
		height: 640,
		aspect: 1.0,
		touchId: "gouache",
		subjectId: "shell",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "gouache-shell",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of opaque color planes, underpainting and brush-mark primitives; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:gouache-shell-medium-r1:v1:review-20260925",
		hasAlpha: false,
	},
	{
		id: "gouache-photo-frame-frame-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/gouache/photo-frame-frame.webp",
		format: "webp",
		width: 1536,
		height: 1152,
		aspect: 1.333333,
		touchId: "gouache",
		subjectId: "photo-frame",
		role: "frame",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "gouache-photo-frame",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of opaque color planes, underpainting and brush-mark primitives; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:gouache-photo-frame-frame-r1:v1:review-20260925",
		hasAlpha: false,
	},
	{
		id: "gouache-heading-band-heading-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/gouache/heading-band-heading.webp",
		format: "webp",
		width: 1536,
		height: 192,
		aspect: 8.0,
		touchId: "gouache",
		subjectId: "heading-band",
		role: "heading",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 32,
		maxPrintWidthMm: 128,
		originalityGroupId: "gouache-heading-band",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of opaque color planes, underpainting and brush-mark primitives; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:gouache-heading-band-heading-r1:v1:review-20260925",
		hasAlpha: false,
	},
	{
		id: "gouache-sticky-note-tab-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/gouache/sticky-note-tab.webp",
		format: "webp",
		width: 1536,
		height: 512,
		aspect: 3.0,
		touchId: "gouache",
		subjectId: "sticky-note",
		role: "tab",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "gouache-sticky-note",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of opaque color planes, underpainting and brush-mark primitives; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:gouache-sticky-note-tab-r1:v1:review-20260925",
		hasAlpha: false,
	},
	{
		id: "gouache-ticket-label-label-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/gouache/ticket-label-label.webp",
		format: "webp",
		width: 1536,
		height: 768,
		aspect: 2.0,
		touchId: "gouache",
		subjectId: "ticket-label",
		role: "label",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 128,
		originalityGroupId: "gouache-ticket-label",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of opaque color planes, underpainting and brush-mark primitives; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:gouache-ticket-label-label-r1:v1:review-20260925",
		hasAlpha: false,
	},
	{
		id: "gouache-measurement-rule-rule-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/gouache/measurement-rule-rule.webp",
		format: "webp",
		width: 1536,
		height: 48,
		aspect: 32.0,
		touchId: "gouache",
		subjectId: "measurement-rule",
		role: "rule",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 28,
		maxPrintWidthMm: 128,
		originalityGroupId: "gouache-measurement-rule",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of opaque color planes, underpainting and brush-mark primitives; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:gouache-measurement-rule-rule-r1:v1:review-20260925",
		hasAlpha: false,
	},
	{
		id: "gouache-grid-panel-panel-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/gouache/grid-panel-panel.webp",
		format: "webp",
		width: 1536,
		height: 1152,
		aspect: 1.333333,
		touchId: "gouache",
		subjectId: "grid-panel",
		role: "panel",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "gouache-grid-panel",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of opaque color planes, underpainting and brush-mark primitives; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:gouache-grid-panel-panel-r1:v1:review-20260925",
		hasAlpha: false,
	},
	{
		id: "gouache-straight-arrow-straight-arrow-r1",
		revision: 1,
		sourcePath:
			"../../assets/artwork/gouache/straight-arrow-straight-arrow.webp",
		format: "webp",
		width: 900,
		height: 300,
		aspect: 3.0,
		touchId: "gouache",
		subjectId: "straight-arrow",
		role: "straight-arrow",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 30,
		originalityGroupId: "gouache-straight-arrow",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of opaque color planes, underpainting and brush-mark primitives; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId:
			"artwork:gouache-straight-arrow-straight-arrow-r1:v1:review-20260925",
		hasAlpha: false,
	},
	{
		id: "gouache-turn-arrow-turn-arrow-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/gouache/turn-arrow-turn-arrow.webp",
		format: "webp",
		width: 900,
		height: 300,
		aspect: 3.0,
		touchId: "gouache",
		subjectId: "turn-arrow",
		role: "turn-arrow",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 30,
		originalityGroupId: "gouache-turn-arrow",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of opaque color planes, underpainting and brush-mark primitives; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:gouache-turn-arrow-turn-arrow-r1:v1:review-20260925",
		hasAlpha: false,
	},
	{
		id: "gouache-route-route-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/gouache/route-route.webp",
		format: "webp",
		width: 600,
		height: 1200,
		aspect: 0.5,
		touchId: "gouache",
		subjectId: "route",
		role: "route",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 14,
		maxPrintWidthMm: 30,
		originalityGroupId: "gouache-route",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of opaque color planes, underpainting and brush-mark primitives; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: "artwork:gouache-route-route-r1:v1:review-20260925",
		hasAlpha: false,
	},
	{
		id: "gouache-season-pattern-season-pattern-r1",
		revision: 1,
		sourcePath:
			"../../assets/artwork/gouache/season-pattern-season-pattern.webp",
		format: "webp",
		width: 1000,
		height: 1000,
		aspect: 1.0,
		touchId: "gouache",
		subjectId: "season-pattern",
		role: "season-pattern",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 36,
		maxPrintWidthMm: 40,
		originalityGroupId: "gouache-season-pattern",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of opaque color planes, underpainting and brush-mark primitives; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId:
			"artwork:gouache-season-pattern-season-pattern-r1:v1:review-20260925",
		hasAlpha: false,
		views: [
			{ id: "spring", x: 0, y: 0, width: 500, height: 500 },
			{ id: "summer", x: 500, y: 0, width: 500, height: 500 },
			{ id: "autumn", x: 0, y: 500, width: 500, height: 500 },
			{ id: "winter", x: 500, y: 500, width: 500, height: 500 },
		],
	},
];
