/** Generated by scripts/generatePublishedArtworkUrls.mjs; only active art enters the product bundle. */
import published0 from "../../assets/artwork/brush/airplane-medium.svg?url";
import published1 from "../../assets/artwork/brush/bag-medium.svg?url";
import published2 from "../../assets/artwork/brush/car-medium.svg?url";
import published3 from "../../assets/artwork/brush/flower-medium.svg?url";
import published4 from "../../assets/artwork/brush/grid-panel-panel.svg?url";
import published5 from "../../assets/artwork/brush/heading-band-heading.svg?url";
import published6 from "../../assets/artwork/brush/leaf-medium.svg?url";
import published7 from "../../assets/artwork/brush/machiya-grid-hero.svg?url";
import published8 from "../../assets/artwork/brush/measurement-rule-rule.svg?url";
import published9 from "../../assets/artwork/brush/mountain-hero.svg?url";
import published10 from "../../assets/artwork/brush/photo-frame-frame.svg?url";
import published11 from "../../assets/artwork/brush/roof-arch-hero.svg?url";
import published12 from "../../assets/artwork/brush/route-route.svg?url";
import published13 from "../../assets/artwork/brush/sea-hero.svg?url";
import published14 from "../../assets/artwork/brush/season-pattern-season-pattern.svg?url";
import published15 from "../../assets/artwork/brush/shell-medium.svg?url";
import published16 from "../../assets/artwork/brush/sticky-note-tab.svg?url";
import published17 from "../../assets/artwork/brush/straight-arrow-straight-arrow.svg?url";
import published18 from "../../assets/artwork/brush/street-hero.svg?url";
import published19 from "../../assets/artwork/brush/tableware-medium.svg?url";
import published20 from "../../assets/artwork/brush/ticket-label-label.svg?url";
import published21 from "../../assets/artwork/brush/train-medium.svg?url";
import published22 from "../../assets/artwork/brush/turn-arrow-turn-arrow.svg?url";
import published23 from "../../assets/artwork/brush/urban-window-railway-hero.svg?url";
import published24 from "../../assets/artwork/chalk/airplane-medium.webp?url";
import published25 from "../../assets/artwork/chalk/bag-medium.webp?url";
import published26 from "../../assets/artwork/chalk/car-medium.webp?url";
import published27 from "../../assets/artwork/chalk/flower-medium.webp?url";
import published28 from "../../assets/artwork/chalk/grid-panel-panel.webp?url";
import published29 from "../../assets/artwork/chalk/heading-band-heading.webp?url";
import published30 from "../../assets/artwork/chalk/leaf-medium.webp?url";
import published31 from "../../assets/artwork/chalk/machiya-grid-hero.webp?url";
import published32 from "../../assets/artwork/chalk/measurement-rule-rule.webp?url";
import published33 from "../../assets/artwork/chalk/mountain-hero.webp?url";
import published34 from "../../assets/artwork/chalk/photo-frame-frame.webp?url";
import published35 from "../../assets/artwork/chalk/roof-arch-hero.webp?url";
import published36 from "../../assets/artwork/chalk/route-route.webp?url";
import published37 from "../../assets/artwork/chalk/sea-hero.webp?url";
import published38 from "../../assets/artwork/chalk/season-pattern-season-pattern.webp?url";
import published39 from "../../assets/artwork/chalk/shell-medium.webp?url";
import published40 from "../../assets/artwork/chalk/sticky-note-tab.webp?url";
import published41 from "../../assets/artwork/chalk/straight-arrow-straight-arrow.webp?url";
import published42 from "../../assets/artwork/chalk/street-hero.webp?url";
import published43 from "../../assets/artwork/chalk/tableware-medium.webp?url";
import published44 from "../../assets/artwork/chalk/ticket-label-label.webp?url";
import published45 from "../../assets/artwork/chalk/train-medium.webp?url";
import published46 from "../../assets/artwork/chalk/turn-arrow-turn-arrow.webp?url";
import published47 from "../../assets/artwork/chalk/urban-window-railway-hero.webp?url";
import published48 from "../../assets/artwork/cut-paper/airplane-medium.svg?url";
import published49 from "../../assets/artwork/cut-paper/bag-medium.svg?url";
import published50 from "../../assets/artwork/cut-paper/car-medium.svg?url";
import published51 from "../../assets/artwork/cut-paper/flower-medium.svg?url";
import published52 from "../../assets/artwork/cut-paper/grid-panel-panel.svg?url";
import published53 from "../../assets/artwork/cut-paper/heading-band-heading.svg?url";
import published54 from "../../assets/artwork/cut-paper/leaf-medium.svg?url";
import published55 from "../../assets/artwork/cut-paper/machiya-grid-hero.svg?url";
import published56 from "../../assets/artwork/cut-paper/measurement-rule-rule.svg?url";
import published57 from "../../assets/artwork/cut-paper/mountain-hero.svg?url";
import published58 from "../../assets/artwork/cut-paper/photo-frame-frame.svg?url";
import published59 from "../../assets/artwork/cut-paper/roof-arch-hero.svg?url";
import published60 from "../../assets/artwork/cut-paper/route-route.svg?url";
import published61 from "../../assets/artwork/cut-paper/sea-hero.svg?url";
import published62 from "../../assets/artwork/cut-paper/season-pattern-season-pattern.svg?url";
import published63 from "../../assets/artwork/cut-paper/shell-medium.svg?url";
import published64 from "../../assets/artwork/cut-paper/sticky-note-tab.svg?url";
import published65 from "../../assets/artwork/cut-paper/straight-arrow-straight-arrow.svg?url";
import published66 from "../../assets/artwork/cut-paper/street-hero.svg?url";
import published67 from "../../assets/artwork/cut-paper/tableware-medium.svg?url";
import published68 from "../../assets/artwork/cut-paper/ticket-label-label.svg?url";
import published69 from "../../assets/artwork/cut-paper/train-medium.svg?url";
import published70 from "../../assets/artwork/cut-paper/turn-arrow-turn-arrow.svg?url";
import published71 from "../../assets/artwork/cut-paper/urban-window-railway-hero.svg?url";
import published72 from "../../assets/artwork/engraving/airplane-medium.svg?url";
import published73 from "../../assets/artwork/engraving/bag-medium.svg?url";
import published74 from "../../assets/artwork/engraving/car-medium.svg?url";
import published75 from "../../assets/artwork/engraving/flower-medium.svg?url";
import published76 from "../../assets/artwork/engraving/grid-panel-panel.svg?url";
import published77 from "../../assets/artwork/engraving/heading-band-heading.svg?url";
import published78 from "../../assets/artwork/engraving/leaf-medium.svg?url";
import published79 from "../../assets/artwork/engraving/machiya-grid-hero.svg?url";
import published80 from "../../assets/artwork/engraving/measurement-rule-rule.svg?url";
import published81 from "../../assets/artwork/engraving/mountain-hero.svg?url";
import published82 from "../../assets/artwork/engraving/photo-frame-frame.svg?url";
import published83 from "../../assets/artwork/engraving/roof-arch-hero.svg?url";
import published84 from "../../assets/artwork/engraving/route-route.svg?url";
import published85 from "../../assets/artwork/engraving/sea-hero.svg?url";
import published86 from "../../assets/artwork/engraving/season-pattern-season-pattern.svg?url";
import published87 from "../../assets/artwork/engraving/shell-medium.svg?url";
import published88 from "../../assets/artwork/engraving/sticky-note-tab.svg?url";
import published89 from "../../assets/artwork/engraving/straight-arrow-straight-arrow.svg?url";
import published90 from "../../assets/artwork/engraving/street-hero.svg?url";
import published91 from "../../assets/artwork/engraving/tableware-medium.svg?url";
import published92 from "../../assets/artwork/engraving/ticket-label-label.svg?url";
import published93 from "../../assets/artwork/engraving/train-medium.svg?url";
import published94 from "../../assets/artwork/engraving/turn-arrow-turn-arrow.svg?url";
import published95 from "../../assets/artwork/engraving/urban-window-railway-hero.svg?url";
import published96 from "../../assets/artwork/gouache/airplane-medium.webp?url";
import published97 from "../../assets/artwork/gouache/bag-medium.webp?url";
import published98 from "../../assets/artwork/gouache/car-medium.webp?url";
import published99 from "../../assets/artwork/gouache/flower-medium.webp?url";
import published100 from "../../assets/artwork/gouache/grid-panel-panel.webp?url";
import published101 from "../../assets/artwork/gouache/heading-band-heading.webp?url";
import published102 from "../../assets/artwork/gouache/leaf-medium.webp?url";
import published103 from "../../assets/artwork/gouache/machiya-grid-hero.webp?url";
import published104 from "../../assets/artwork/gouache/measurement-rule-rule.webp?url";
import published105 from "../../assets/artwork/gouache/mountain-hero.webp?url";
import published106 from "../../assets/artwork/gouache/photo-frame-frame.webp?url";
import published107 from "../../assets/artwork/gouache/roof-arch-hero.webp?url";
import published108 from "../../assets/artwork/gouache/route-route.webp?url";
import published109 from "../../assets/artwork/gouache/sea-hero.webp?url";
import published110 from "../../assets/artwork/gouache/season-pattern-season-pattern.webp?url";
import published111 from "../../assets/artwork/gouache/shell-medium.webp?url";
import published112 from "../../assets/artwork/gouache/sticky-note-tab.webp?url";
import published113 from "../../assets/artwork/gouache/straight-arrow-straight-arrow.webp?url";
import published114 from "../../assets/artwork/gouache/street-hero.webp?url";
import published115 from "../../assets/artwork/gouache/tableware-medium.webp?url";
import published116 from "../../assets/artwork/gouache/ticket-label-label.webp?url";
import published117 from "../../assets/artwork/gouache/train-medium.webp?url";
import published118 from "../../assets/artwork/gouache/turn-arrow-turn-arrow.webp?url";
import published119 from "../../assets/artwork/gouache/urban-window-railway-hero.webp?url";
import published120 from "../../assets/artwork/ink-wash/airplane-medium.webp?url";
import published121 from "../../assets/artwork/ink-wash/bag-medium.webp?url";
import published122 from "../../assets/artwork/ink-wash/car-medium.webp?url";
import published123 from "../../assets/artwork/ink-wash/flower-medium.webp?url";
import published124 from "../../assets/artwork/ink-wash/grid-panel-panel.webp?url";
import published125 from "../../assets/artwork/ink-wash/heading-band-heading.webp?url";
import published126 from "../../assets/artwork/ink-wash/leaf-medium.webp?url";
import published127 from "../../assets/artwork/ink-wash/machiya-grid-hero.webp?url";
import published128 from "../../assets/artwork/ink-wash/measurement-rule-rule.webp?url";
import published129 from "../../assets/artwork/ink-wash/mountain-hero.webp?url";
import published130 from "../../assets/artwork/ink-wash/photo-frame-frame.webp?url";
import published131 from "../../assets/artwork/ink-wash/roof-arch-hero.webp?url";
import published132 from "../../assets/artwork/ink-wash/route-route.webp?url";
import published133 from "../../assets/artwork/ink-wash/sea-hero.webp?url";
import published134 from "../../assets/artwork/ink-wash/season-pattern-season-pattern.webp?url";
import published135 from "../../assets/artwork/ink-wash/shell-medium.webp?url";
import published136 from "../../assets/artwork/ink-wash/sticky-note-tab.webp?url";
import published137 from "../../assets/artwork/ink-wash/straight-arrow-straight-arrow.webp?url";
import published138 from "../../assets/artwork/ink-wash/street-hero.webp?url";
import published139 from "../../assets/artwork/ink-wash/tableware-medium.webp?url";
import published140 from "../../assets/artwork/ink-wash/ticket-label-label.webp?url";
import published141 from "../../assets/artwork/ink-wash/train-medium.webp?url";
import published142 from "../../assets/artwork/ink-wash/turn-arrow-turn-arrow.webp?url";
import published143 from "../../assets/artwork/ink-wash/urban-window-railway-hero.webp?url";
import published144 from "../../assets/artwork/pencil/airplane-medium.svg?url";
import published145 from "../../assets/artwork/pencil/bag-medium.svg?url";
import published146 from "../../assets/artwork/pencil/car-medium.svg?url";
import published147 from "../../assets/artwork/pencil/flower-medium.svg?url";
import published148 from "../../assets/artwork/pencil/grid-panel-panel.svg?url";
import published149 from "../../assets/artwork/pencil/heading-band-heading.svg?url";
import published150 from "../../assets/artwork/pencil/leaf-medium.svg?url";
import published151 from "../../assets/artwork/pencil/machiya-grid-hero.svg?url";
import published152 from "../../assets/artwork/pencil/measurement-rule-rule.svg?url";
import published153 from "../../assets/artwork/pencil/mountain-hero.svg?url";
import published154 from "../../assets/artwork/pencil/photo-frame-frame.svg?url";
import published155 from "../../assets/artwork/pencil/roof-arch-hero.svg?url";
import published156 from "../../assets/artwork/pencil/route-route.svg?url";
import published157 from "../../assets/artwork/pencil/sea-hero.svg?url";
import published158 from "../../assets/artwork/pencil/season-pattern-season-pattern.svg?url";
import published159 from "../../assets/artwork/pencil/shell-medium.svg?url";
import published160 from "../../assets/artwork/pencil/sticky-note-tab.svg?url";
import published161 from "../../assets/artwork/pencil/straight-arrow-straight-arrow.svg?url";
import published162 from "../../assets/artwork/pencil/street-hero.svg?url";
import published163 from "../../assets/artwork/pencil/tableware-medium.svg?url";
import published164 from "../../assets/artwork/pencil/ticket-label-label.svg?url";
import published165 from "../../assets/artwork/pencil/train-medium.svg?url";
import published166 from "../../assets/artwork/pencil/turn-arrow-turn-arrow.svg?url";
import published167 from "../../assets/artwork/pencil/urban-window-railway-hero.svg?url";
import published168 from "../../assets/artwork/pixel/airplane-medium.svg?url";
import published169 from "../../assets/artwork/pixel/bag-medium.svg?url";
import published170 from "../../assets/artwork/pixel/car-medium.svg?url";
import published171 from "../../assets/artwork/pixel/flower-medium.svg?url";
import published172 from "../../assets/artwork/pixel/grid-panel-panel.svg?url";
import published173 from "../../assets/artwork/pixel/heading-band-heading.svg?url";
import published174 from "../../assets/artwork/pixel/leaf-medium.svg?url";
import published175 from "../../assets/artwork/pixel/machiya-grid-hero.svg?url";
import published176 from "../../assets/artwork/pixel/measurement-rule-rule.svg?url";
import published177 from "../../assets/artwork/pixel/mountain-hero.svg?url";
import published178 from "../../assets/artwork/pixel/photo-frame-frame.svg?url";
import published179 from "../../assets/artwork/pixel/roof-arch-hero.svg?url";
import published180 from "../../assets/artwork/pixel/route-route.svg?url";
import published181 from "../../assets/artwork/pixel/sea-hero.svg?url";
import published182 from "../../assets/artwork/pixel/season-pattern-season-pattern.svg?url";
import published183 from "../../assets/artwork/pixel/shell-medium.svg?url";
import published184 from "../../assets/artwork/pixel/sticky-note-tab.svg?url";
import published185 from "../../assets/artwork/pixel/straight-arrow-straight-arrow.svg?url";
import published186 from "../../assets/artwork/pixel/street-hero.svg?url";
import published187 from "../../assets/artwork/pixel/tableware-medium.svg?url";
import published188 from "../../assets/artwork/pixel/ticket-label-label.svg?url";
import published189 from "../../assets/artwork/pixel/train-medium.svg?url";
import published190 from "../../assets/artwork/pixel/turn-arrow-turn-arrow.svg?url";
import published191 from "../../assets/artwork/pixel/urban-window-railway-hero.svg?url";
import published192 from "../../assets/artwork/risograph/airplane-medium.svg?url";
import published193 from "../../assets/artwork/risograph/bag-medium.svg?url";
import published194 from "../../assets/artwork/risograph/car-medium.svg?url";
import published195 from "../../assets/artwork/risograph/flower-medium.svg?url";
import published196 from "../../assets/artwork/risograph/grid-panel-panel.svg?url";
import published197 from "../../assets/artwork/risograph/heading-band-heading.svg?url";
import published198 from "../../assets/artwork/risograph/leaf-medium.svg?url";
import published199 from "../../assets/artwork/risograph/machiya-grid-hero.svg?url";
import published200 from "../../assets/artwork/risograph/measurement-rule-rule.svg?url";
import published201 from "../../assets/artwork/risograph/mountain-hero.svg?url";
import published202 from "../../assets/artwork/risograph/photo-frame-frame.svg?url";
import published203 from "../../assets/artwork/risograph/roof-arch-hero.svg?url";
import published204 from "../../assets/artwork/risograph/route-route.svg?url";
import published205 from "../../assets/artwork/risograph/sea-hero.svg?url";
import published206 from "../../assets/artwork/risograph/season-pattern-season-pattern.svg?url";
import published207 from "../../assets/artwork/risograph/shell-medium.svg?url";
import published208 from "../../assets/artwork/risograph/sticky-note-tab.svg?url";
import published209 from "../../assets/artwork/risograph/straight-arrow-straight-arrow.svg?url";
import published210 from "../../assets/artwork/risograph/street-hero.svg?url";
import published211 from "../../assets/artwork/risograph/tableware-medium.svg?url";
import published212 from "../../assets/artwork/risograph/ticket-label-label.svg?url";
import published213 from "../../assets/artwork/risograph/train-medium.svg?url";
import published214 from "../../assets/artwork/risograph/turn-arrow-turn-arrow.svg?url";
import published215 from "../../assets/artwork/risograph/urban-window-railway-hero.svg?url";
import published216 from "../../assets/artwork/screenprint/airplane-medium.svg?url";
import published217 from "../../assets/artwork/screenprint/bag-medium.svg?url";
import published218 from "../../assets/artwork/screenprint/car-medium.svg?url";
import published219 from "../../assets/artwork/screenprint/flower-medium.svg?url";
import published220 from "../../assets/artwork/screenprint/grid-panel-panel.svg?url";
import published221 from "../../assets/artwork/screenprint/heading-band-heading.svg?url";
import published222 from "../../assets/artwork/screenprint/leaf-medium.svg?url";
import published223 from "../../assets/artwork/screenprint/machiya-grid-hero.svg?url";
import published224 from "../../assets/artwork/screenprint/measurement-rule-rule.svg?url";
import published225 from "../../assets/artwork/screenprint/mountain-hero.svg?url";
import published226 from "../../assets/artwork/screenprint/photo-frame-frame.svg?url";
import published227 from "../../assets/artwork/screenprint/roof-arch-hero.svg?url";
import published228 from "../../assets/artwork/screenprint/route-route.svg?url";
import published229 from "../../assets/artwork/screenprint/sea-hero.svg?url";
import published230 from "../../assets/artwork/screenprint/season-pattern-season-pattern.svg?url";
import published231 from "../../assets/artwork/screenprint/shell-medium.svg?url";
import published232 from "../../assets/artwork/screenprint/sticky-note-tab.svg?url";
import published233 from "../../assets/artwork/screenprint/straight-arrow-straight-arrow.svg?url";
import published234 from "../../assets/artwork/screenprint/street-hero.svg?url";
import published235 from "../../assets/artwork/screenprint/tableware-medium.svg?url";
import published236 from "../../assets/artwork/screenprint/ticket-label-label.svg?url";
import published237 from "../../assets/artwork/screenprint/train-medium.svg?url";
import published238 from "../../assets/artwork/screenprint/turn-arrow-turn-arrow.svg?url";
import published239 from "../../assets/artwork/screenprint/urban-window-railway-hero.svg?url";
import published240 from "../../assets/artwork/technical/airplane-medium.svg?url";
import published241 from "../../assets/artwork/technical/bag-medium.svg?url";
import published242 from "../../assets/artwork/technical/car-medium.svg?url";
import published243 from "../../assets/artwork/technical/flower-medium.svg?url";
import published244 from "../../assets/artwork/technical/grid-panel-panel.svg?url";
import published245 from "../../assets/artwork/technical/heading-band-heading.svg?url";
import published246 from "../../assets/artwork/technical/leaf-medium.svg?url";
import published247 from "../../assets/artwork/technical/machiya-grid-hero.svg?url";
import published248 from "../../assets/artwork/technical/measurement-rule-rule.svg?url";
import published249 from "../../assets/artwork/technical/mountain-hero.svg?url";
import published250 from "../../assets/artwork/technical/photo-frame-frame.svg?url";
import published251 from "../../assets/artwork/technical/roof-arch-hero.svg?url";
import published252 from "../../assets/artwork/technical/route-route.svg?url";
import published253 from "../../assets/artwork/technical/sea-hero.svg?url";
import published254 from "../../assets/artwork/technical/season-pattern-season-pattern.svg?url";
import published255 from "../../assets/artwork/technical/shell-medium.svg?url";
import published256 from "../../assets/artwork/technical/sticky-note-tab.svg?url";
import published257 from "../../assets/artwork/technical/straight-arrow-straight-arrow.svg?url";
import published258 from "../../assets/artwork/technical/street-hero.svg?url";
import published259 from "../../assets/artwork/technical/tableware-medium.svg?url";
import published260 from "../../assets/artwork/technical/ticket-label-label.svg?url";
import published261 from "../../assets/artwork/technical/train-medium.svg?url";
import published262 from "../../assets/artwork/technical/turn-arrow-turn-arrow.svg?url";
import published263 from "../../assets/artwork/technical/urban-window-railway-hero.svg?url";
import published264 from "../../assets/artwork/woodcut/airplane-medium.svg?url";
import published265 from "../../assets/artwork/woodcut/bag-medium.svg?url";
import published266 from "../../assets/artwork/woodcut/car-medium.svg?url";
import published267 from "../../assets/artwork/woodcut/flower-medium.svg?url";
import published268 from "../../assets/artwork/woodcut/grid-panel-panel.svg?url";
import published269 from "../../assets/artwork/woodcut/heading-band-heading.svg?url";
import published270 from "../../assets/artwork/woodcut/leaf-medium.svg?url";
import published271 from "../../assets/artwork/woodcut/machiya-grid-hero.svg?url";
import published272 from "../../assets/artwork/woodcut/measurement-rule-rule.svg?url";
import published273 from "../../assets/artwork/woodcut/mountain-hero.svg?url";
import published274 from "../../assets/artwork/woodcut/photo-frame-frame.svg?url";
import published275 from "../../assets/artwork/woodcut/roof-arch-hero.svg?url";
import published276 from "../../assets/artwork/woodcut/route-route.svg?url";
import published277 from "../../assets/artwork/woodcut/sea-hero.svg?url";
import published278 from "../../assets/artwork/woodcut/season-pattern-season-pattern.svg?url";
import published279 from "../../assets/artwork/woodcut/shell-medium.svg?url";
import published280 from "../../assets/artwork/woodcut/sticky-note-tab.svg?url";
import published281 from "../../assets/artwork/woodcut/straight-arrow-straight-arrow.svg?url";
import published282 from "../../assets/artwork/woodcut/street-hero.svg?url";
import published283 from "../../assets/artwork/woodcut/tableware-medium.svg?url";
import published284 from "../../assets/artwork/woodcut/ticket-label-label.svg?url";
import published285 from "../../assets/artwork/woodcut/train-medium.svg?url";
import published286 from "../../assets/artwork/woodcut/turn-arrow-turn-arrow.svg?url";
import published287 from "../../assets/artwork/woodcut/urban-window-railway-hero.svg?url";

export const PUBLISHED_ARTWORK_URLS: Readonly<Record<string, string>> =
	Object.freeze({
		"../../assets/artwork/brush/airplane-medium.svg": published0,
		"../../assets/artwork/brush/bag-medium.svg": published1,
		"../../assets/artwork/brush/car-medium.svg": published2,
		"../../assets/artwork/brush/flower-medium.svg": published3,
		"../../assets/artwork/brush/grid-panel-panel.svg": published4,
		"../../assets/artwork/brush/heading-band-heading.svg": published5,
		"../../assets/artwork/brush/leaf-medium.svg": published6,
		"../../assets/artwork/brush/machiya-grid-hero.svg": published7,
		"../../assets/artwork/brush/measurement-rule-rule.svg": published8,
		"../../assets/artwork/brush/mountain-hero.svg": published9,
		"../../assets/artwork/brush/photo-frame-frame.svg": published10,
		"../../assets/artwork/brush/roof-arch-hero.svg": published11,
		"../../assets/artwork/brush/route-route.svg": published12,
		"../../assets/artwork/brush/sea-hero.svg": published13,
		"../../assets/artwork/brush/season-pattern-season-pattern.svg": published14,
		"../../assets/artwork/brush/shell-medium.svg": published15,
		"../../assets/artwork/brush/sticky-note-tab.svg": published16,
		"../../assets/artwork/brush/straight-arrow-straight-arrow.svg": published17,
		"../../assets/artwork/brush/street-hero.svg": published18,
		"../../assets/artwork/brush/tableware-medium.svg": published19,
		"../../assets/artwork/brush/ticket-label-label.svg": published20,
		"../../assets/artwork/brush/train-medium.svg": published21,
		"../../assets/artwork/brush/turn-arrow-turn-arrow.svg": published22,
		"../../assets/artwork/brush/urban-window-railway-hero.svg": published23,
		"../../assets/artwork/chalk/airplane-medium.webp": published24,
		"../../assets/artwork/chalk/bag-medium.webp": published25,
		"../../assets/artwork/chalk/car-medium.webp": published26,
		"../../assets/artwork/chalk/flower-medium.webp": published27,
		"../../assets/artwork/chalk/grid-panel-panel.webp": published28,
		"../../assets/artwork/chalk/heading-band-heading.webp": published29,
		"../../assets/artwork/chalk/leaf-medium.webp": published30,
		"../../assets/artwork/chalk/machiya-grid-hero.webp": published31,
		"../../assets/artwork/chalk/measurement-rule-rule.webp": published32,
		"../../assets/artwork/chalk/mountain-hero.webp": published33,
		"../../assets/artwork/chalk/photo-frame-frame.webp": published34,
		"../../assets/artwork/chalk/roof-arch-hero.webp": published35,
		"../../assets/artwork/chalk/route-route.webp": published36,
		"../../assets/artwork/chalk/sea-hero.webp": published37,
		"../../assets/artwork/chalk/season-pattern-season-pattern.webp":
			published38,
		"../../assets/artwork/chalk/shell-medium.webp": published39,
		"../../assets/artwork/chalk/sticky-note-tab.webp": published40,
		"../../assets/artwork/chalk/straight-arrow-straight-arrow.webp":
			published41,
		"../../assets/artwork/chalk/street-hero.webp": published42,
		"../../assets/artwork/chalk/tableware-medium.webp": published43,
		"../../assets/artwork/chalk/ticket-label-label.webp": published44,
		"../../assets/artwork/chalk/train-medium.webp": published45,
		"../../assets/artwork/chalk/turn-arrow-turn-arrow.webp": published46,
		"../../assets/artwork/chalk/urban-window-railway-hero.webp": published47,
		"../../assets/artwork/cut-paper/airplane-medium.svg": published48,
		"../../assets/artwork/cut-paper/bag-medium.svg": published49,
		"../../assets/artwork/cut-paper/car-medium.svg": published50,
		"../../assets/artwork/cut-paper/flower-medium.svg": published51,
		"../../assets/artwork/cut-paper/grid-panel-panel.svg": published52,
		"../../assets/artwork/cut-paper/heading-band-heading.svg": published53,
		"../../assets/artwork/cut-paper/leaf-medium.svg": published54,
		"../../assets/artwork/cut-paper/machiya-grid-hero.svg": published55,
		"../../assets/artwork/cut-paper/measurement-rule-rule.svg": published56,
		"../../assets/artwork/cut-paper/mountain-hero.svg": published57,
		"../../assets/artwork/cut-paper/photo-frame-frame.svg": published58,
		"../../assets/artwork/cut-paper/roof-arch-hero.svg": published59,
		"../../assets/artwork/cut-paper/route-route.svg": published60,
		"../../assets/artwork/cut-paper/sea-hero.svg": published61,
		"../../assets/artwork/cut-paper/season-pattern-season-pattern.svg":
			published62,
		"../../assets/artwork/cut-paper/shell-medium.svg": published63,
		"../../assets/artwork/cut-paper/sticky-note-tab.svg": published64,
		"../../assets/artwork/cut-paper/straight-arrow-straight-arrow.svg":
			published65,
		"../../assets/artwork/cut-paper/street-hero.svg": published66,
		"../../assets/artwork/cut-paper/tableware-medium.svg": published67,
		"../../assets/artwork/cut-paper/ticket-label-label.svg": published68,
		"../../assets/artwork/cut-paper/train-medium.svg": published69,
		"../../assets/artwork/cut-paper/turn-arrow-turn-arrow.svg": published70,
		"../../assets/artwork/cut-paper/urban-window-railway-hero.svg": published71,
		"../../assets/artwork/engraving/airplane-medium.svg": published72,
		"../../assets/artwork/engraving/bag-medium.svg": published73,
		"../../assets/artwork/engraving/car-medium.svg": published74,
		"../../assets/artwork/engraving/flower-medium.svg": published75,
		"../../assets/artwork/engraving/grid-panel-panel.svg": published76,
		"../../assets/artwork/engraving/heading-band-heading.svg": published77,
		"../../assets/artwork/engraving/leaf-medium.svg": published78,
		"../../assets/artwork/engraving/machiya-grid-hero.svg": published79,
		"../../assets/artwork/engraving/measurement-rule-rule.svg": published80,
		"../../assets/artwork/engraving/mountain-hero.svg": published81,
		"../../assets/artwork/engraving/photo-frame-frame.svg": published82,
		"../../assets/artwork/engraving/roof-arch-hero.svg": published83,
		"../../assets/artwork/engraving/route-route.svg": published84,
		"../../assets/artwork/engraving/sea-hero.svg": published85,
		"../../assets/artwork/engraving/season-pattern-season-pattern.svg":
			published86,
		"../../assets/artwork/engraving/shell-medium.svg": published87,
		"../../assets/artwork/engraving/sticky-note-tab.svg": published88,
		"../../assets/artwork/engraving/straight-arrow-straight-arrow.svg":
			published89,
		"../../assets/artwork/engraving/street-hero.svg": published90,
		"../../assets/artwork/engraving/tableware-medium.svg": published91,
		"../../assets/artwork/engraving/ticket-label-label.svg": published92,
		"../../assets/artwork/engraving/train-medium.svg": published93,
		"../../assets/artwork/engraving/turn-arrow-turn-arrow.svg": published94,
		"../../assets/artwork/engraving/urban-window-railway-hero.svg": published95,
		"../../assets/artwork/gouache/airplane-medium.webp": published96,
		"../../assets/artwork/gouache/bag-medium.webp": published97,
		"../../assets/artwork/gouache/car-medium.webp": published98,
		"../../assets/artwork/gouache/flower-medium.webp": published99,
		"../../assets/artwork/gouache/grid-panel-panel.webp": published100,
		"../../assets/artwork/gouache/heading-band-heading.webp": published101,
		"../../assets/artwork/gouache/leaf-medium.webp": published102,
		"../../assets/artwork/gouache/machiya-grid-hero.webp": published103,
		"../../assets/artwork/gouache/measurement-rule-rule.webp": published104,
		"../../assets/artwork/gouache/mountain-hero.webp": published105,
		"../../assets/artwork/gouache/photo-frame-frame.webp": published106,
		"../../assets/artwork/gouache/roof-arch-hero.webp": published107,
		"../../assets/artwork/gouache/route-route.webp": published108,
		"../../assets/artwork/gouache/sea-hero.webp": published109,
		"../../assets/artwork/gouache/season-pattern-season-pattern.webp":
			published110,
		"../../assets/artwork/gouache/shell-medium.webp": published111,
		"../../assets/artwork/gouache/sticky-note-tab.webp": published112,
		"../../assets/artwork/gouache/straight-arrow-straight-arrow.webp":
			published113,
		"../../assets/artwork/gouache/street-hero.webp": published114,
		"../../assets/artwork/gouache/tableware-medium.webp": published115,
		"../../assets/artwork/gouache/ticket-label-label.webp": published116,
		"../../assets/artwork/gouache/train-medium.webp": published117,
		"../../assets/artwork/gouache/turn-arrow-turn-arrow.webp": published118,
		"../../assets/artwork/gouache/urban-window-railway-hero.webp": published119,
		"../../assets/artwork/ink-wash/airplane-medium.webp": published120,
		"../../assets/artwork/ink-wash/bag-medium.webp": published121,
		"../../assets/artwork/ink-wash/car-medium.webp": published122,
		"../../assets/artwork/ink-wash/flower-medium.webp": published123,
		"../../assets/artwork/ink-wash/grid-panel-panel.webp": published124,
		"../../assets/artwork/ink-wash/heading-band-heading.webp": published125,
		"../../assets/artwork/ink-wash/leaf-medium.webp": published126,
		"../../assets/artwork/ink-wash/machiya-grid-hero.webp": published127,
		"../../assets/artwork/ink-wash/measurement-rule-rule.webp": published128,
		"../../assets/artwork/ink-wash/mountain-hero.webp": published129,
		"../../assets/artwork/ink-wash/photo-frame-frame.webp": published130,
		"../../assets/artwork/ink-wash/roof-arch-hero.webp": published131,
		"../../assets/artwork/ink-wash/route-route.webp": published132,
		"../../assets/artwork/ink-wash/sea-hero.webp": published133,
		"../../assets/artwork/ink-wash/season-pattern-season-pattern.webp":
			published134,
		"../../assets/artwork/ink-wash/shell-medium.webp": published135,
		"../../assets/artwork/ink-wash/sticky-note-tab.webp": published136,
		"../../assets/artwork/ink-wash/straight-arrow-straight-arrow.webp":
			published137,
		"../../assets/artwork/ink-wash/street-hero.webp": published138,
		"../../assets/artwork/ink-wash/tableware-medium.webp": published139,
		"../../assets/artwork/ink-wash/ticket-label-label.webp": published140,
		"../../assets/artwork/ink-wash/train-medium.webp": published141,
		"../../assets/artwork/ink-wash/turn-arrow-turn-arrow.webp": published142,
		"../../assets/artwork/ink-wash/urban-window-railway-hero.webp":
			published143,
		"../../assets/artwork/pencil/airplane-medium.svg": published144,
		"../../assets/artwork/pencil/bag-medium.svg": published145,
		"../../assets/artwork/pencil/car-medium.svg": published146,
		"../../assets/artwork/pencil/flower-medium.svg": published147,
		"../../assets/artwork/pencil/grid-panel-panel.svg": published148,
		"../../assets/artwork/pencil/heading-band-heading.svg": published149,
		"../../assets/artwork/pencil/leaf-medium.svg": published150,
		"../../assets/artwork/pencil/machiya-grid-hero.svg": published151,
		"../../assets/artwork/pencil/measurement-rule-rule.svg": published152,
		"../../assets/artwork/pencil/mountain-hero.svg": published153,
		"../../assets/artwork/pencil/photo-frame-frame.svg": published154,
		"../../assets/artwork/pencil/roof-arch-hero.svg": published155,
		"../../assets/artwork/pencil/route-route.svg": published156,
		"../../assets/artwork/pencil/sea-hero.svg": published157,
		"../../assets/artwork/pencil/season-pattern-season-pattern.svg":
			published158,
		"../../assets/artwork/pencil/shell-medium.svg": published159,
		"../../assets/artwork/pencil/sticky-note-tab.svg": published160,
		"../../assets/artwork/pencil/straight-arrow-straight-arrow.svg":
			published161,
		"../../assets/artwork/pencil/street-hero.svg": published162,
		"../../assets/artwork/pencil/tableware-medium.svg": published163,
		"../../assets/artwork/pencil/ticket-label-label.svg": published164,
		"../../assets/artwork/pencil/train-medium.svg": published165,
		"../../assets/artwork/pencil/turn-arrow-turn-arrow.svg": published166,
		"../../assets/artwork/pencil/urban-window-railway-hero.svg": published167,
		"../../assets/artwork/pixel/airplane-medium.svg": published168,
		"../../assets/artwork/pixel/bag-medium.svg": published169,
		"../../assets/artwork/pixel/car-medium.svg": published170,
		"../../assets/artwork/pixel/flower-medium.svg": published171,
		"../../assets/artwork/pixel/grid-panel-panel.svg": published172,
		"../../assets/artwork/pixel/heading-band-heading.svg": published173,
		"../../assets/artwork/pixel/leaf-medium.svg": published174,
		"../../assets/artwork/pixel/machiya-grid-hero.svg": published175,
		"../../assets/artwork/pixel/measurement-rule-rule.svg": published176,
		"../../assets/artwork/pixel/mountain-hero.svg": published177,
		"../../assets/artwork/pixel/photo-frame-frame.svg": published178,
		"../../assets/artwork/pixel/roof-arch-hero.svg": published179,
		"../../assets/artwork/pixel/route-route.svg": published180,
		"../../assets/artwork/pixel/sea-hero.svg": published181,
		"../../assets/artwork/pixel/season-pattern-season-pattern.svg":
			published182,
		"../../assets/artwork/pixel/shell-medium.svg": published183,
		"../../assets/artwork/pixel/sticky-note-tab.svg": published184,
		"../../assets/artwork/pixel/straight-arrow-straight-arrow.svg":
			published185,
		"../../assets/artwork/pixel/street-hero.svg": published186,
		"../../assets/artwork/pixel/tableware-medium.svg": published187,
		"../../assets/artwork/pixel/ticket-label-label.svg": published188,
		"../../assets/artwork/pixel/train-medium.svg": published189,
		"../../assets/artwork/pixel/turn-arrow-turn-arrow.svg": published190,
		"../../assets/artwork/pixel/urban-window-railway-hero.svg": published191,
		"../../assets/artwork/risograph/airplane-medium.svg": published192,
		"../../assets/artwork/risograph/bag-medium.svg": published193,
		"../../assets/artwork/risograph/car-medium.svg": published194,
		"../../assets/artwork/risograph/flower-medium.svg": published195,
		"../../assets/artwork/risograph/grid-panel-panel.svg": published196,
		"../../assets/artwork/risograph/heading-band-heading.svg": published197,
		"../../assets/artwork/risograph/leaf-medium.svg": published198,
		"../../assets/artwork/risograph/machiya-grid-hero.svg": published199,
		"../../assets/artwork/risograph/measurement-rule-rule.svg": published200,
		"../../assets/artwork/risograph/mountain-hero.svg": published201,
		"../../assets/artwork/risograph/photo-frame-frame.svg": published202,
		"../../assets/artwork/risograph/roof-arch-hero.svg": published203,
		"../../assets/artwork/risograph/route-route.svg": published204,
		"../../assets/artwork/risograph/sea-hero.svg": published205,
		"../../assets/artwork/risograph/season-pattern-season-pattern.svg":
			published206,
		"../../assets/artwork/risograph/shell-medium.svg": published207,
		"../../assets/artwork/risograph/sticky-note-tab.svg": published208,
		"../../assets/artwork/risograph/straight-arrow-straight-arrow.svg":
			published209,
		"../../assets/artwork/risograph/street-hero.svg": published210,
		"../../assets/artwork/risograph/tableware-medium.svg": published211,
		"../../assets/artwork/risograph/ticket-label-label.svg": published212,
		"../../assets/artwork/risograph/train-medium.svg": published213,
		"../../assets/artwork/risograph/turn-arrow-turn-arrow.svg": published214,
		"../../assets/artwork/risograph/urban-window-railway-hero.svg":
			published215,
		"../../assets/artwork/screenprint/airplane-medium.svg": published216,
		"../../assets/artwork/screenprint/bag-medium.svg": published217,
		"../../assets/artwork/screenprint/car-medium.svg": published218,
		"../../assets/artwork/screenprint/flower-medium.svg": published219,
		"../../assets/artwork/screenprint/grid-panel-panel.svg": published220,
		"../../assets/artwork/screenprint/heading-band-heading.svg": published221,
		"../../assets/artwork/screenprint/leaf-medium.svg": published222,
		"../../assets/artwork/screenprint/machiya-grid-hero.svg": published223,
		"../../assets/artwork/screenprint/measurement-rule-rule.svg": published224,
		"../../assets/artwork/screenprint/mountain-hero.svg": published225,
		"../../assets/artwork/screenprint/photo-frame-frame.svg": published226,
		"../../assets/artwork/screenprint/roof-arch-hero.svg": published227,
		"../../assets/artwork/screenprint/route-route.svg": published228,
		"../../assets/artwork/screenprint/sea-hero.svg": published229,
		"../../assets/artwork/screenprint/season-pattern-season-pattern.svg":
			published230,
		"../../assets/artwork/screenprint/shell-medium.svg": published231,
		"../../assets/artwork/screenprint/sticky-note-tab.svg": published232,
		"../../assets/artwork/screenprint/straight-arrow-straight-arrow.svg":
			published233,
		"../../assets/artwork/screenprint/street-hero.svg": published234,
		"../../assets/artwork/screenprint/tableware-medium.svg": published235,
		"../../assets/artwork/screenprint/ticket-label-label.svg": published236,
		"../../assets/artwork/screenprint/train-medium.svg": published237,
		"../../assets/artwork/screenprint/turn-arrow-turn-arrow.svg": published238,
		"../../assets/artwork/screenprint/urban-window-railway-hero.svg":
			published239,
		"../../assets/artwork/technical/airplane-medium.svg": published240,
		"../../assets/artwork/technical/bag-medium.svg": published241,
		"../../assets/artwork/technical/car-medium.svg": published242,
		"../../assets/artwork/technical/flower-medium.svg": published243,
		"../../assets/artwork/technical/grid-panel-panel.svg": published244,
		"../../assets/artwork/technical/heading-band-heading.svg": published245,
		"../../assets/artwork/technical/leaf-medium.svg": published246,
		"../../assets/artwork/technical/machiya-grid-hero.svg": published247,
		"../../assets/artwork/technical/measurement-rule-rule.svg": published248,
		"../../assets/artwork/technical/mountain-hero.svg": published249,
		"../../assets/artwork/technical/photo-frame-frame.svg": published250,
		"../../assets/artwork/technical/roof-arch-hero.svg": published251,
		"../../assets/artwork/technical/route-route.svg": published252,
		"../../assets/artwork/technical/sea-hero.svg": published253,
		"../../assets/artwork/technical/season-pattern-season-pattern.svg":
			published254,
		"../../assets/artwork/technical/shell-medium.svg": published255,
		"../../assets/artwork/technical/sticky-note-tab.svg": published256,
		"../../assets/artwork/technical/straight-arrow-straight-arrow.svg":
			published257,
		"../../assets/artwork/technical/street-hero.svg": published258,
		"../../assets/artwork/technical/tableware-medium.svg": published259,
		"../../assets/artwork/technical/ticket-label-label.svg": published260,
		"../../assets/artwork/technical/train-medium.svg": published261,
		"../../assets/artwork/technical/turn-arrow-turn-arrow.svg": published262,
		"../../assets/artwork/technical/urban-window-railway-hero.svg":
			published263,
		"../../assets/artwork/woodcut/airplane-medium.svg": published264,
		"../../assets/artwork/woodcut/bag-medium.svg": published265,
		"../../assets/artwork/woodcut/car-medium.svg": published266,
		"../../assets/artwork/woodcut/flower-medium.svg": published267,
		"../../assets/artwork/woodcut/grid-panel-panel.svg": published268,
		"../../assets/artwork/woodcut/heading-band-heading.svg": published269,
		"../../assets/artwork/woodcut/leaf-medium.svg": published270,
		"../../assets/artwork/woodcut/machiya-grid-hero.svg": published271,
		"../../assets/artwork/woodcut/measurement-rule-rule.svg": published272,
		"../../assets/artwork/woodcut/mountain-hero.svg": published273,
		"../../assets/artwork/woodcut/photo-frame-frame.svg": published274,
		"../../assets/artwork/woodcut/roof-arch-hero.svg": published275,
		"../../assets/artwork/woodcut/route-route.svg": published276,
		"../../assets/artwork/woodcut/sea-hero.svg": published277,
		"../../assets/artwork/woodcut/season-pattern-season-pattern.svg":
			published278,
		"../../assets/artwork/woodcut/shell-medium.svg": published279,
		"../../assets/artwork/woodcut/sticky-note-tab.svg": published280,
		"../../assets/artwork/woodcut/straight-arrow-straight-arrow.svg":
			published281,
		"../../assets/artwork/woodcut/street-hero.svg": published282,
		"../../assets/artwork/woodcut/tableware-medium.svg": published283,
		"../../assets/artwork/woodcut/ticket-label-label.svg": published284,
		"../../assets/artwork/woodcut/train-medium.svg": published285,
		"../../assets/artwork/woodcut/turn-arrow-turn-arrow.svg": published286,
		"../../assets/artwork/woodcut/urban-window-railway-hero.svg": published287,
	});
