import type { ArtworkDefinition } from "../../../theme/artwork/types";

/** risograph originals; draft until visual review. */
export const ARTWORK_MANIFEST: readonly ArtworkDefinition[] = [
	{
		id: "risograph-airplane-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/risograph/airplane-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "risograph",
		subjectId: "airplane",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "risograph-airplane",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Two-plate risograph with deliberate color registration offset, halftone fields and overprint.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "risograph-bag-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/risograph/bag-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "risograph",
		subjectId: "bag",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "risograph-bag",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Two-plate risograph with deliberate color registration offset, halftone fields and overprint.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "risograph-car-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/risograph/car-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "risograph",
		subjectId: "car",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "risograph-car",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Two-plate risograph with deliberate color registration offset, halftone fields and overprint.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "risograph-flower-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/risograph/flower-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "risograph",
		subjectId: "flower",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "risograph-flower",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Two-plate risograph with deliberate color registration offset, halftone fields and overprint.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "risograph-grid-panel-panel-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/risograph/grid-panel-panel.svg",
		format: "svg",
		width: 320,
		height: 240,
		aspect: 1.333333,
		touchId: "risograph",
		subjectId: "grid-panel",
		role: "panel",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 18,
		maxPrintWidthMm: 128,
		originalityGroupId: "risograph-grid-panel",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Two-plate risograph with deliberate color registration offset, halftone fields and overprint.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "risograph-heading-band-heading-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/risograph/heading-band-heading.svg",
		format: "svg",
		width: 320,
		height: 40,
		aspect: 8.0,
		touchId: "risograph",
		subjectId: "heading-band",
		role: "heading",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 32,
		maxPrintWidthMm: 128,
		originalityGroupId: "risograph-heading-band",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Two-plate risograph with deliberate color registration offset, halftone fields and overprint.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "risograph-leaf-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/risograph/leaf-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "risograph",
		subjectId: "leaf",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "risograph-leaf",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Two-plate risograph with deliberate color registration offset, halftone fields and overprint.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "risograph-machiya-grid-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/risograph/machiya-grid-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "risograph",
		subjectId: "machiya-grid",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "risograph-machiya-grid",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Two-plate risograph with deliberate color registration offset, halftone fields and overprint.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "risograph-measurement-rule-rule-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/risograph/measurement-rule-rule.svg",
		format: "svg",
		width: 320,
		height: 10,
		aspect: 32.0,
		touchId: "risograph",
		subjectId: "measurement-rule",
		role: "rule",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 24,
		maxPrintWidthMm: 128,
		originalityGroupId: "risograph-measurement-rule",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Two-plate risograph with deliberate color registration offset, halftone fields and overprint.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "risograph-mountain-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/risograph/mountain-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "risograph",
		subjectId: "mountain",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "risograph-mountain",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Two-plate risograph with deliberate color registration offset, halftone fields and overprint.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "risograph-photo-frame-frame-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/risograph/photo-frame-frame.svg",
		format: "svg",
		width: 320,
		height: 240,
		aspect: 1.333333,
		touchId: "risograph",
		subjectId: "photo-frame",
		role: "frame",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 18,
		maxPrintWidthMm: 128,
		originalityGroupId: "risograph-photo-frame",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Two-plate risograph with deliberate color registration offset, halftone fields and overprint.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "risograph-roof-arch-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/risograph/roof-arch-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "risograph",
		subjectId: "roof-arch",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "risograph-roof-arch",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Two-plate risograph with deliberate color registration offset, halftone fields and overprint.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "risograph-route-route-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/risograph/route-route.svg",
		format: "svg",
		width: 120,
		height: 240,
		aspect: 0.5,
		touchId: "risograph",
		subjectId: "route",
		role: "route",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 14,
		maxPrintWidthMm: 30,
		originalityGroupId: "risograph-route",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Two-plate risograph with deliberate color registration offset, halftone fields and overprint.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "risograph-sea-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/risograph/sea-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "risograph",
		subjectId: "sea",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "risograph-sea",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Two-plate risograph with deliberate color registration offset, halftone fields and overprint.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "risograph-season-pattern-season-pattern-r1",
		revision: 1,
		sourcePath:
			"../../assets/artwork/risograph/season-pattern-season-pattern.svg",
		format: "svg",
		width: 1000,
		height: 1000,
		aspect: 1.0,
		touchId: "risograph",
		subjectId: "season-pattern",
		role: "season-pattern",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 30,
		maxPrintWidthMm: 40,
		originalityGroupId: "risograph-season-pattern",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Two-plate risograph with deliberate color registration offset, halftone fields and overprint.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
		views: [
			{ id: "spring", x: 0, y: 0, width: 500, height: 500 },
			{ id: "summer", x: 500, y: 0, width: 500, height: 500 },
			{ id: "autumn", x: 0, y: 500, width: 500, height: 500 },
			{ id: "winter", x: 500, y: 500, width: 500, height: 500 },
		],
	},
	{
		id: "risograph-shell-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/risograph/shell-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "risograph",
		subjectId: "shell",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "risograph-shell",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Two-plate risograph with deliberate color registration offset, halftone fields and overprint.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "risograph-sticky-note-tab-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/risograph/sticky-note-tab.svg",
		format: "svg",
		width: 300,
		height: 100,
		aspect: 3.0,
		touchId: "risograph",
		subjectId: "sticky-note",
		role: "tab",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 20,
		maxPrintWidthMm: 128,
		originalityGroupId: "risograph-sticky-note",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Two-plate risograph with deliberate color registration offset, halftone fields and overprint.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "risograph-straight-arrow-straight-arrow-r1",
		revision: 1,
		sourcePath:
			"../../assets/artwork/risograph/straight-arrow-straight-arrow.svg",
		format: "svg",
		width: 300,
		height: 100,
		aspect: 3.0,
		touchId: "risograph",
		subjectId: "straight-arrow",
		role: "straight-arrow",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 30,
		originalityGroupId: "risograph-straight-arrow",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Two-plate risograph with deliberate color registration offset, halftone fields and overprint.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "risograph-street-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/risograph/street-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "risograph",
		subjectId: "street",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "risograph-street",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Two-plate risograph with deliberate color registration offset, halftone fields and overprint.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "risograph-tableware-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/risograph/tableware-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "risograph",
		subjectId: "tableware",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "risograph-tableware",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Two-plate risograph with deliberate color registration offset, halftone fields and overprint.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "risograph-ticket-label-label-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/risograph/ticket-label-label.svg",
		format: "svg",
		width: 200,
		height: 100,
		aspect: 2.0,
		touchId: "risograph",
		subjectId: "ticket-label",
		role: "label",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 14,
		maxPrintWidthMm: 128,
		originalityGroupId: "risograph-ticket-label",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Two-plate risograph with deliberate color registration offset, halftone fields and overprint.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "risograph-train-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/risograph/train-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "risograph",
		subjectId: "train",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "risograph-train",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Two-plate risograph with deliberate color registration offset, halftone fields and overprint.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "risograph-turn-arrow-turn-arrow-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/risograph/turn-arrow-turn-arrow.svg",
		format: "svg",
		width: 300,
		height: 100,
		aspect: 3.0,
		touchId: "risograph",
		subjectId: "turn-arrow",
		role: "turn-arrow",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 30,
		originalityGroupId: "risograph-turn-arrow",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Two-plate risograph with deliberate color registration offset, halftone fields and overprint.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "risograph-urban-window-railway-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/risograph/urban-window-railway-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "risograph",
		subjectId: "urban-window-railway",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "risograph-urban-window-railway",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Two-plate risograph with deliberate color registration offset, halftone fields and overprint.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
];
