import type { ArtworkDefinition } from "../../../theme/artwork/types";

/** brush originals; draft until visual review. */
export const ARTWORK_MANIFEST: readonly ArtworkDefinition[] = [
	{
		id: "brush-airplane-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/brush/airplane-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "brush",
		subjectId: "airplane",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "brush-airplane",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Brush strokes with pressure changes, tapered starts, broad bellies and dry lifted ends.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "brush-bag-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/brush/bag-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "brush",
		subjectId: "bag",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "brush-bag",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Brush strokes with pressure changes, tapered starts, broad bellies and dry lifted ends.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "brush-car-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/brush/car-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "brush",
		subjectId: "car",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "brush-car",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Brush strokes with pressure changes, tapered starts, broad bellies and dry lifted ends.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "brush-flower-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/brush/flower-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "brush",
		subjectId: "flower",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "brush-flower",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Brush strokes with pressure changes, tapered starts, broad bellies and dry lifted ends.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "brush-grid-panel-panel-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/brush/grid-panel-panel.svg",
		format: "svg",
		width: 320,
		height: 240,
		aspect: 1.333333,
		touchId: "brush",
		subjectId: "grid-panel",
		role: "panel",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 18,
		maxPrintWidthMm: 128,
		originalityGroupId: "brush-grid-panel",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Brush strokes with pressure changes, tapered starts, broad bellies and dry lifted ends.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "brush-heading-band-heading-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/brush/heading-band-heading.svg",
		format: "svg",
		width: 320,
		height: 40,
		aspect: 8.0,
		touchId: "brush",
		subjectId: "heading-band",
		role: "heading",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 32,
		maxPrintWidthMm: 128,
		originalityGroupId: "brush-heading-band",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Brush strokes with pressure changes, tapered starts, broad bellies and dry lifted ends.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "brush-leaf-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/brush/leaf-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "brush",
		subjectId: "leaf",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "brush-leaf",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Brush strokes with pressure changes, tapered starts, broad bellies and dry lifted ends.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "brush-machiya-grid-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/brush/machiya-grid-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "brush",
		subjectId: "machiya-grid",
		role: "hero",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "brush-machiya-grid",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Brush strokes with pressure changes, tapered starts, broad bellies and dry lifted ends.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "brush-measurement-rule-rule-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/brush/measurement-rule-rule.svg",
		format: "svg",
		width: 320,
		height: 10,
		aspect: 32.0,
		touchId: "brush",
		subjectId: "measurement-rule",
		role: "rule",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 24,
		maxPrintWidthMm: 128,
		originalityGroupId: "brush-measurement-rule",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Brush strokes with pressure changes, tapered starts, broad bellies and dry lifted ends.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "brush-mountain-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/brush/mountain-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "brush",
		subjectId: "mountain",
		role: "hero",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "brush-mountain",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Brush strokes with pressure changes, tapered starts, broad bellies and dry lifted ends.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "brush-photo-frame-frame-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/brush/photo-frame-frame.svg",
		format: "svg",
		width: 320,
		height: 240,
		aspect: 1.333333,
		touchId: "brush",
		subjectId: "photo-frame",
		role: "frame",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 18,
		maxPrintWidthMm: 128,
		originalityGroupId: "brush-photo-frame",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Brush strokes with pressure changes, tapered starts, broad bellies and dry lifted ends.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "brush-roof-arch-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/brush/roof-arch-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "brush",
		subjectId: "roof-arch",
		role: "hero",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "brush-roof-arch",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Brush strokes with pressure changes, tapered starts, broad bellies and dry lifted ends.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "brush-route-route-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/brush/route-route.svg",
		format: "svg",
		width: 120,
		height: 240,
		aspect: 0.5,
		touchId: "brush",
		subjectId: "route",
		role: "route",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 14,
		maxPrintWidthMm: 30,
		originalityGroupId: "brush-route",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Brush strokes with pressure changes, tapered starts, broad bellies and dry lifted ends.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "brush-sea-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/brush/sea-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "brush",
		subjectId: "sea",
		role: "hero",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "brush-sea",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Brush strokes with pressure changes, tapered starts, broad bellies and dry lifted ends.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "brush-season-pattern-season-pattern-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/brush/season-pattern-season-pattern.svg",
		format: "svg",
		width: 1000,
		height: 1000,
		aspect: 1.0,
		touchId: "brush",
		subjectId: "season-pattern",
		role: "season-pattern",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 30,
		maxPrintWidthMm: 40,
		originalityGroupId: "brush-season-pattern",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Brush strokes with pressure changes, tapered starts, broad bellies and dry lifted ends.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
		views: [
			{ id: "spring", x: 0, y: 0, width: 500, height: 500 },
			{ id: "summer", x: 500, y: 0, width: 500, height: 500 },
			{ id: "autumn", x: 0, y: 500, width: 500, height: 500 },
			{ id: "winter", x: 500, y: 500, width: 500, height: 500 },
		],
	},
	{
		id: "brush-shell-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/brush/shell-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "brush",
		subjectId: "shell",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "brush-shell",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Brush strokes with pressure changes, tapered starts, broad bellies and dry lifted ends.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "brush-sticky-note-tab-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/brush/sticky-note-tab.svg",
		format: "svg",
		width: 300,
		height: 100,
		aspect: 3.0,
		touchId: "brush",
		subjectId: "sticky-note",
		role: "tab",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 20,
		maxPrintWidthMm: 128,
		originalityGroupId: "brush-sticky-note",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Brush strokes with pressure changes, tapered starts, broad bellies and dry lifted ends.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "brush-straight-arrow-straight-arrow-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/brush/straight-arrow-straight-arrow.svg",
		format: "svg",
		width: 300,
		height: 100,
		aspect: 3.0,
		touchId: "brush",
		subjectId: "straight-arrow",
		role: "straight-arrow",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 30,
		originalityGroupId: "brush-straight-arrow",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Brush strokes with pressure changes, tapered starts, broad bellies and dry lifted ends.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "brush-street-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/brush/street-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "brush",
		subjectId: "street",
		role: "hero",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "brush-street",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Brush strokes with pressure changes, tapered starts, broad bellies and dry lifted ends.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "brush-tableware-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/brush/tableware-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "brush",
		subjectId: "tableware",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "brush-tableware",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Brush strokes with pressure changes, tapered starts, broad bellies and dry lifted ends.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "brush-ticket-label-label-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/brush/ticket-label-label.svg",
		format: "svg",
		width: 200,
		height: 100,
		aspect: 2.0,
		touchId: "brush",
		subjectId: "ticket-label",
		role: "label",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 14,
		maxPrintWidthMm: 128,
		originalityGroupId: "brush-ticket-label",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Brush strokes with pressure changes, tapered starts, broad bellies and dry lifted ends.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "brush-train-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/brush/train-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "brush",
		subjectId: "train",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "brush-train",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Brush strokes with pressure changes, tapered starts, broad bellies and dry lifted ends.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "brush-turn-arrow-turn-arrow-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/brush/turn-arrow-turn-arrow.svg",
		format: "svg",
		width: 300,
		height: 100,
		aspect: 3.0,
		touchId: "brush",
		subjectId: "turn-arrow",
		role: "turn-arrow",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 30,
		originalityGroupId: "brush-turn-arrow",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Brush strokes with pressure changes, tapered starts, broad bellies and dry lifted ends.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "brush-urban-window-railway-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/brush/urban-window-railway-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "brush",
		subjectId: "urban-window-railway",
		role: "hero",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "brush-urban-window-railway",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Brush strokes with pressure changes, tapered starts, broad bellies and dry lifted ends.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
];
