import type { ArtworkDefinition } from "../../../theme/artwork/types";

/** pixel originals; draft until visual review. */
export const ARTWORK_MANIFEST: readonly ArtworkDefinition[] = [
	{
		id: "pixel-airplane-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pixel/airplane-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "pixel",
		subjectId: "airplane",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "pixel-airplane",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Grid-snapped pixel forms with stepped contours, clustered square cells and crisp edges.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:pixel-airplane-medium-r1:v1:review-20260925",
	},
	{
		id: "pixel-bag-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pixel/bag-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "pixel",
		subjectId: "bag",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "pixel-bag",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Grid-snapped pixel forms with stepped contours, clustered square cells and crisp edges.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:pixel-bag-medium-r1:v1:review-20260925",
	},
	{
		id: "pixel-car-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pixel/car-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "pixel",
		subjectId: "car",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "pixel-car",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Grid-snapped pixel forms with stepped contours, clustered square cells and crisp edges.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:pixel-car-medium-r1:v1:review-20260925",
	},
	{
		id: "pixel-flower-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pixel/flower-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "pixel",
		subjectId: "flower",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "pixel-flower",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Grid-snapped pixel forms with stepped contours, clustered square cells and crisp edges.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:pixel-flower-medium-r1:v1:review-20260925",
	},
	{
		id: "pixel-grid-panel-panel-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pixel/grid-panel-panel.svg",
		format: "svg",
		width: 320,
		height: 240,
		aspect: 1.333333,
		touchId: "pixel",
		subjectId: "grid-panel",
		role: "panel",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 18,
		maxPrintWidthMm: 128,
		originalityGroupId: "pixel-grid-panel",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Grid-snapped pixel forms with stepped contours, clustered square cells and crisp edges.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:pixel-grid-panel-panel-r1:v1:review-20260925",
	},
	{
		id: "pixel-heading-band-heading-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pixel/heading-band-heading.svg",
		format: "svg",
		width: 320,
		height: 40,
		aspect: 8.0,
		touchId: "pixel",
		subjectId: "heading-band",
		role: "heading",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 32,
		maxPrintWidthMm: 128,
		originalityGroupId: "pixel-heading-band",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Grid-snapped pixel forms with stepped contours, clustered square cells and crisp edges.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:pixel-heading-band-heading-r1:v1:review-20260925",
	},
	{
		id: "pixel-leaf-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pixel/leaf-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "pixel",
		subjectId: "leaf",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "pixel-leaf",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Grid-snapped pixel forms with stepped contours, clustered square cells and crisp edges.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:pixel-leaf-medium-r1:v1:review-20260925",
	},
	{
		id: "pixel-machiya-grid-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pixel/machiya-grid-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "pixel",
		subjectId: "machiya-grid",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "pixel-machiya-grid",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Grid-snapped pixel forms with stepped contours, clustered square cells and crisp edges.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:pixel-machiya-grid-hero-r1:v1:review-20260925",
	},
	{
		id: "pixel-measurement-rule-rule-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pixel/measurement-rule-rule.svg",
		format: "svg",
		width: 320,
		height: 10,
		aspect: 32.0,
		touchId: "pixel",
		subjectId: "measurement-rule",
		role: "rule",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 24,
		maxPrintWidthMm: 128,
		originalityGroupId: "pixel-measurement-rule",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Grid-snapped pixel forms with stepped contours, clustered square cells and crisp edges.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:pixel-measurement-rule-rule-r1:v1:review-20260925",
	},
	{
		id: "pixel-mountain-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pixel/mountain-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "pixel",
		subjectId: "mountain",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "pixel-mountain",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Grid-snapped pixel forms with stepped contours, clustered square cells and crisp edges.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:pixel-mountain-hero-r1:v1:review-20260925",
	},
	{
		id: "pixel-photo-frame-frame-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pixel/photo-frame-frame.svg",
		format: "svg",
		width: 320,
		height: 240,
		aspect: 1.333333,
		touchId: "pixel",
		subjectId: "photo-frame",
		role: "frame",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 18,
		maxPrintWidthMm: 128,
		originalityGroupId: "pixel-photo-frame",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Grid-snapped pixel forms with stepped contours, clustered square cells and crisp edges.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:pixel-photo-frame-frame-r1:v1:review-20260925",
	},
	{
		id: "pixel-roof-arch-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pixel/roof-arch-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "pixel",
		subjectId: "roof-arch",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "pixel-roof-arch",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Grid-snapped pixel forms with stepped contours, clustered square cells and crisp edges.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:pixel-roof-arch-hero-r1:v1:review-20260925",
	},
	{
		id: "pixel-route-route-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pixel/route-route.svg",
		format: "svg",
		width: 120,
		height: 240,
		aspect: 0.5,
		touchId: "pixel",
		subjectId: "route",
		role: "route",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 14,
		maxPrintWidthMm: 30,
		originalityGroupId: "pixel-route",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Grid-snapped pixel forms with stepped contours, clustered square cells and crisp edges.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:pixel-route-route-r1:v1:review-20260925",
	},
	{
		id: "pixel-sea-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pixel/sea-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "pixel",
		subjectId: "sea",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "pixel-sea",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Grid-snapped pixel forms with stepped contours, clustered square cells and crisp edges.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:pixel-sea-hero-r1:v1:review-20260925",
	},
	{
		id: "pixel-season-pattern-season-pattern-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pixel/season-pattern-season-pattern.svg",
		format: "svg",
		width: 1000,
		height: 1000,
		aspect: 1.0,
		touchId: "pixel",
		subjectId: "season-pattern",
		role: "season-pattern",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 30,
		maxPrintWidthMm: 40,
		originalityGroupId: "pixel-season-pattern",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Grid-snapped pixel forms with stepped contours, clustered square cells and crisp edges.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId:
			"artwork:pixel-season-pattern-season-pattern-r1:v1:review-20260925",
		views: [
			{ id: "spring", x: 0, y: 0, width: 500, height: 500 },
			{ id: "summer", x: 500, y: 0, width: 500, height: 500 },
			{ id: "autumn", x: 0, y: 500, width: 500, height: 500 },
			{ id: "winter", x: 500, y: 500, width: 500, height: 500 },
		],
	},
	{
		id: "pixel-shell-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pixel/shell-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "pixel",
		subjectId: "shell",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "pixel-shell",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Grid-snapped pixel forms with stepped contours, clustered square cells and crisp edges.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:pixel-shell-medium-r1:v1:review-20260925",
	},
	{
		id: "pixel-sticky-note-tab-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pixel/sticky-note-tab.svg",
		format: "svg",
		width: 300,
		height: 100,
		aspect: 3.0,
		touchId: "pixel",
		subjectId: "sticky-note",
		role: "tab",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 20,
		maxPrintWidthMm: 128,
		originalityGroupId: "pixel-sticky-note",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Grid-snapped pixel forms with stepped contours, clustered square cells and crisp edges.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:pixel-sticky-note-tab-r1:v1:review-20260925",
	},
	{
		id: "pixel-straight-arrow-straight-arrow-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pixel/straight-arrow-straight-arrow.svg",
		format: "svg",
		width: 300,
		height: 100,
		aspect: 3.0,
		touchId: "pixel",
		subjectId: "straight-arrow",
		role: "straight-arrow",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 30,
		originalityGroupId: "pixel-straight-arrow",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Grid-snapped pixel forms with stepped contours, clustered square cells and crisp edges.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId:
			"artwork:pixel-straight-arrow-straight-arrow-r1:v1:review-20260925",
	},
	{
		id: "pixel-street-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pixel/street-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "pixel",
		subjectId: "street",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "pixel-street",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Grid-snapped pixel forms with stepped contours, clustered square cells and crisp edges.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:pixel-street-hero-r1:v1:review-20260925",
	},
	{
		id: "pixel-tableware-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pixel/tableware-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "pixel",
		subjectId: "tableware",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "pixel-tableware",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Grid-snapped pixel forms with stepped contours, clustered square cells and crisp edges.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:pixel-tableware-medium-r1:v1:review-20260925",
	},
	{
		id: "pixel-ticket-label-label-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pixel/ticket-label-label.svg",
		format: "svg",
		width: 200,
		height: 100,
		aspect: 2.0,
		touchId: "pixel",
		subjectId: "ticket-label",
		role: "label",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 14,
		maxPrintWidthMm: 128,
		originalityGroupId: "pixel-ticket-label",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Grid-snapped pixel forms with stepped contours, clustered square cells and crisp edges.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:pixel-ticket-label-label-r1:v1:review-20260925",
	},
	{
		id: "pixel-train-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pixel/train-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "pixel",
		subjectId: "train",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "pixel-train",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Grid-snapped pixel forms with stepped contours, clustered square cells and crisp edges.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:pixel-train-medium-r1:v1:review-20260925",
	},
	{
		id: "pixel-turn-arrow-turn-arrow-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pixel/turn-arrow-turn-arrow.svg",
		format: "svg",
		width: 300,
		height: 100,
		aspect: 3.0,
		touchId: "pixel",
		subjectId: "turn-arrow",
		role: "turn-arrow",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 30,
		originalityGroupId: "pixel-turn-arrow",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Grid-snapped pixel forms with stepped contours, clustered square cells and crisp edges.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:pixel-turn-arrow-turn-arrow-r1:v1:review-20260925",
	},
	{
		id: "pixel-urban-window-railway-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pixel/urban-window-railway-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "pixel",
		subjectId: "urban-window-railway",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "pixel-urban-window-railway",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Grid-snapped pixel forms with stepped contours, clustered square cells and crisp edges.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:pixel-urban-window-railway-hero-r1:v1:review-20260925",
	},
];
