ALTER TABLE journey.journey_images
    DROP CONSTRAINT journey_images_visual_style_check,
    ADD CONSTRAINT journey_images_visual_style_check
        CHECK (
            visual_style IS NULL
            OR visual_style IN (
                'none',
                'editorial-photograph',
                'cinematic-photograph',
                'watercolor',
                'gouache',
                'oil-painting',
                'pastel',
                'transparent-watercolor',
                'refined-travel-editorial',
                'luminous-anime-background',
                'retro-travel-poster',
                'cinematic-story',
                'minimal-flat-landmarks',
                'soft-pastel-holiday',
                'watercolor-pencil-sketch',
                'vintage-postcard',
                'quiet-photo-book',
                'sunny-vacation',
                'golden-hour-sentimental',
                'architectural-pen-sketch',
                'travel-icon-collage',
                'paper-cut-storybook',
                'japanese-retro-travel-ad',
                'nordic-earth-minimal',
                'literary-ink-wash',
                'emotional-film-photo',
                'luxury-travel-ad',
                'pop-geometric-travel',
                'seasonal-nature',
                'antique-travel-journal',
                'epic-wide-adventure',
                'quiet-neighborhood',
                'blue-white-urban',
                'tranquil-outdoors',
                'romantic-night-neon',
                'notebook-line-art',
                'elegant-semireal',
                'fantasy-storybook',
                'luminous-youth-anime',
                'miniature-diorama',
                'idealized-photo-illustration',
                'japanese-quiet-minimal',
                'dynamic-vivid-poster',
                'healing-backlight-nature',
                'classic-adventure-novel',
                'limited-color-line-art',
                'natural-travel-photo'
            )
        );
