import type { ArtworkDefinition } from "../../../theme/artwork/types";

/** woodcut originals; draft until visual review. */
export const ARTWORK_MANIFEST: readonly ArtworkDefinition[] = [
	{
		id: "woodcut-airplane-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/woodcut/airplane-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "woodcut",
		subjectId: "airplane",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "woodcut-airplane",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original woodcut treatment with broad ink contours and silhouettes, interrupted edges, and transparent carved grain cuts.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:woodcut-airplane-medium-r1:v1:review-20260925",
	},
	{
		id: "woodcut-bag-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/woodcut/bag-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "woodcut",
		subjectId: "bag",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "woodcut-bag",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original woodcut treatment with broad ink contours and silhouettes, interrupted edges, and transparent carved grain cuts.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:woodcut-bag-medium-r1:v1:review-20260925",
	},
	{
		id: "woodcut-car-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/woodcut/car-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "woodcut",
		subjectId: "car",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "woodcut-car",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original woodcut treatment with broad ink contours and silhouettes, interrupted edges, and transparent carved grain cuts.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:woodcut-car-medium-r1:v1:review-20260925",
	},
	{
		id: "woodcut-flower-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/woodcut/flower-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "woodcut",
		subjectId: "flower",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "woodcut-flower",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original woodcut treatment with broad ink contours and silhouettes, interrupted edges, and transparent carved grain cuts.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:woodcut-flower-medium-r1:v1:review-20260925",
	},
	{
		id: "woodcut-grid-panel-panel-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/woodcut/grid-panel-panel.svg",
		format: "svg",
		width: 320,
		height: 240,
		aspect: 1.333333,
		touchId: "woodcut",
		subjectId: "grid-panel",
		role: "panel",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 18,
		maxPrintWidthMm: 128,
		originalityGroupId: "woodcut-grid-panel",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original woodcut treatment with broad ink contours and silhouettes, interrupted edges, and transparent carved grain cuts.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:woodcut-grid-panel-panel-r1:v1:review-20260925",
	},
	{
		id: "woodcut-heading-band-heading-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/woodcut/heading-band-heading.svg",
		format: "svg",
		width: 320,
		height: 40,
		aspect: 8.0,
		touchId: "woodcut",
		subjectId: "heading-band",
		role: "heading",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 32,
		maxPrintWidthMm: 128,
		originalityGroupId: "woodcut-heading-band",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original woodcut treatment with broad ink contours and silhouettes, interrupted edges, and transparent carved grain cuts.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:woodcut-heading-band-heading-r1:v1:review-20260925",
	},
	{
		id: "woodcut-leaf-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/woodcut/leaf-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "woodcut",
		subjectId: "leaf",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "woodcut-leaf",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original woodcut treatment with broad ink contours and silhouettes, interrupted edges, and transparent carved grain cuts.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:woodcut-leaf-medium-r1:v1:review-20260925",
	},
	{
		id: "woodcut-machiya-grid-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/woodcut/machiya-grid-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "woodcut",
		subjectId: "machiya-grid",
		role: "hero",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "woodcut-machiya-grid",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Hand-composed subject-specific vector geometry with heavy contours and irregular cut-mark accents.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:woodcut-machiya-grid-hero-r1:v1:review-20260925",
	},
	{
		id: "woodcut-measurement-rule-rule-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/woodcut/measurement-rule-rule.svg",
		format: "svg",
		width: 320,
		height: 10,
		aspect: 32.0,
		touchId: "woodcut",
		subjectId: "measurement-rule",
		role: "rule",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 24,
		maxPrintWidthMm: 128,
		originalityGroupId: "woodcut-measurement-rule",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original woodcut treatment with broad ink contours and silhouettes, interrupted edges, and transparent carved grain cuts.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:woodcut-measurement-rule-rule-r1:v1:review-20260925",
	},
	{
		id: "woodcut-mountain-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/woodcut/mountain-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "woodcut",
		subjectId: "mountain",
		role: "hero",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "woodcut-mountain",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Hand-composed subject-specific vector geometry with heavy contours and irregular cut-mark accents.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:woodcut-mountain-hero-r1:v1:review-20260925",
	},
	{
		id: "woodcut-photo-frame-frame-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/woodcut/photo-frame-frame.svg",
		format: "svg",
		width: 320,
		height: 240,
		aspect: 1.333333,
		touchId: "woodcut",
		subjectId: "photo-frame",
		role: "frame",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 18,
		maxPrintWidthMm: 128,
		originalityGroupId: "woodcut-photo-frame",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original woodcut treatment with broad ink contours and silhouettes, interrupted edges, and transparent carved grain cuts.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:woodcut-photo-frame-frame-r1:v1:review-20260925",
	},
	{
		id: "woodcut-roof-arch-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/woodcut/roof-arch-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "woodcut",
		subjectId: "roof-arch",
		role: "hero",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "woodcut-roof-arch",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Hand-composed subject-specific vector geometry with heavy contours and irregular cut-mark accents.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:woodcut-roof-arch-hero-r1:v1:review-20260925",
	},
	{
		id: "woodcut-route-route-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/woodcut/route-route.svg",
		format: "svg",
		width: 120,
		height: 240,
		aspect: 0.5,
		touchId: "woodcut",
		subjectId: "route",
		role: "route",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 14,
		maxPrintWidthMm: 30,
		originalityGroupId: "woodcut-route",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original woodcut treatment with broad ink contours and silhouettes, interrupted edges, and transparent carved grain cuts.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:woodcut-route-route-r1:v1:review-20260925",
	},
	{
		id: "woodcut-sea-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/woodcut/sea-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "woodcut",
		subjectId: "sea",
		role: "hero",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "woodcut-sea",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Hand-composed subject-specific vector geometry with heavy contours and irregular cut-mark accents.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:woodcut-sea-hero-r1:v1:review-20260925",
	},
	{
		id: "woodcut-season-pattern-season-pattern-r1",
		revision: 1,
		sourcePath:
			"../../assets/artwork/woodcut/season-pattern-season-pattern.svg",
		format: "svg",
		width: 1000,
		height: 1000,
		aspect: 1.0,
		touchId: "woodcut",
		subjectId: "season-pattern",
		role: "season-pattern",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 30,
		maxPrintWidthMm: 40,
		originalityGroupId: "woodcut-season-pattern",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original woodcut treatment with broad ink contours and silhouettes, interrupted edges, and transparent carved grain cuts.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId:
			"artwork:woodcut-season-pattern-season-pattern-r1:v1:review-20260925",
		views: [
			{ id: "spring", x: 0, y: 0, width: 500, height: 500 },
			{ id: "summer", x: 500, y: 0, width: 500, height: 500 },
			{ id: "autumn", x: 0, y: 500, width: 500, height: 500 },
			{ id: "winter", x: 500, y: 500, width: 500, height: 500 },
		],
	},
	{
		id: "woodcut-shell-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/woodcut/shell-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "woodcut",
		subjectId: "shell",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "woodcut-shell",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original woodcut treatment with broad ink contours and silhouettes, interrupted edges, and transparent carved grain cuts.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:woodcut-shell-medium-r1:v1:review-20260925",
	},
	{
		id: "woodcut-sticky-note-tab-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/woodcut/sticky-note-tab.svg",
		format: "svg",
		width: 300,
		height: 100,
		aspect: 3.0,
		touchId: "woodcut",
		subjectId: "sticky-note",
		role: "tab",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 20,
		maxPrintWidthMm: 128,
		originalityGroupId: "woodcut-sticky-note",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original woodcut treatment with broad ink contours and silhouettes, interrupted edges, and transparent carved grain cuts.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:woodcut-sticky-note-tab-r1:v1:review-20260925",
	},
	{
		id: "woodcut-straight-arrow-straight-arrow-r1",
		revision: 1,
		sourcePath:
			"../../assets/artwork/woodcut/straight-arrow-straight-arrow.svg",
		format: "svg",
		width: 300,
		height: 100,
		aspect: 3.0,
		touchId: "woodcut",
		subjectId: "straight-arrow",
		role: "straight-arrow",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 30,
		originalityGroupId: "woodcut-straight-arrow",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original woodcut treatment with broad ink contours and silhouettes, interrupted edges, and transparent carved grain cuts.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId:
			"artwork:woodcut-straight-arrow-straight-arrow-r1:v1:review-20260925",
	},
	{
		id: "woodcut-street-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/woodcut/street-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "woodcut",
		subjectId: "street",
		role: "hero",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "woodcut-street",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Hand-composed subject-specific vector geometry with heavy contours and irregular cut-mark accents.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:woodcut-street-hero-r1:v1:review-20260925",
	},
	{
		id: "woodcut-tableware-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/woodcut/tableware-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "woodcut",
		subjectId: "tableware",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "woodcut-tableware",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original woodcut treatment with broad ink contours and silhouettes, interrupted edges, and transparent carved grain cuts.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:woodcut-tableware-medium-r1:v1:review-20260925",
	},
	{
		id: "woodcut-ticket-label-label-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/woodcut/ticket-label-label.svg",
		format: "svg",
		width: 200,
		height: 100,
		aspect: 2.0,
		touchId: "woodcut",
		subjectId: "ticket-label",
		role: "label",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 14,
		maxPrintWidthMm: 128,
		originalityGroupId: "woodcut-ticket-label",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original woodcut treatment with broad ink contours and silhouettes, interrupted edges, and transparent carved grain cuts.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:woodcut-ticket-label-label-r1:v1:review-20260925",
	},
	{
		id: "woodcut-train-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/woodcut/train-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "woodcut",
		subjectId: "train",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "woodcut-train",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original woodcut treatment with broad ink contours and silhouettes, interrupted edges, and transparent carved grain cuts.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:woodcut-train-medium-r1:v1:review-20260925",
	},
	{
		id: "woodcut-turn-arrow-turn-arrow-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/woodcut/turn-arrow-turn-arrow.svg",
		format: "svg",
		width: 300,
		height: 100,
		aspect: 3.0,
		touchId: "woodcut",
		subjectId: "turn-arrow",
		role: "turn-arrow",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 30,
		originalityGroupId: "woodcut-turn-arrow",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original woodcut treatment with broad ink contours and silhouettes, interrupted edges, and transparent carved grain cuts.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:woodcut-turn-arrow-turn-arrow-r1:v1:review-20260925",
	},
	{
		id: "woodcut-urban-window-railway-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/woodcut/urban-window-railway-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "woodcut",
		subjectId: "urban-window-railway",
		role: "hero",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "woodcut-urban-window-railway",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Hand-composed subject-specific vector geometry with heavy contours and irregular cut-mark accents.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:woodcut-urban-window-railway-hero-r1:v1:review-20260925",
	},
];
