export const COVER_VISUAL_STYLES = [
	"editorial-photograph",
	"cinematic-photograph",
	"watercolor",
	"gouache",
	"oil-painting",
	"pastel",
	"transparent-watercolor",
	"refined-travel-editorial",
	"luminous-anime-background",
	"retro-travel-poster",
	"cinematic-story",
	"minimal-flat-landmarks",
	"soft-pastel-holiday",
	"watercolor-pencil-sketch",
	"vintage-postcard",
	"quiet-photo-book",
	"sunny-vacation",
	"golden-hour-sentimental",
	"architectural-pen-sketch",
	"travel-icon-collage",
	"paper-cut-storybook",
	"japanese-retro-travel-ad",
	"nordic-earth-minimal",
	"literary-ink-wash",
	"emotional-film-photo",
	"luxury-travel-ad",
	"pop-geometric-travel",
	"seasonal-nature",
	"antique-travel-journal",
	"epic-wide-adventure",
	"quiet-neighborhood",
	"blue-white-urban",
	"tranquil-outdoors",
	"romantic-night-neon",
	"notebook-line-art",
	"elegant-semireal",
	"fantasy-storybook",
	"luminous-youth-anime",
	"miniature-diorama",
	"idealized-photo-illustration",
	"japanese-quiet-minimal",
	"dynamic-vivid-poster",
	"healing-backlight-nature",
	"classic-adventure-novel",
	"limited-color-line-art",
	"natural-travel-photo",
] as const;

export type CoverVisualStyle = (typeof COVER_VISUAL_STYLES)[number];

export const SOFT_COVER_VISUAL_STYLES = [
	"watercolor",
	"pastel",
	"transparent-watercolor",
	"soft-pastel-holiday",
	"watercolor-pencil-sketch",
	"quiet-photo-book",
	"golden-hour-sentimental",
	"nordic-earth-minimal",
	"literary-ink-wash",
	"emotional-film-photo",
	"antique-travel-journal",
	"quiet-neighborhood",
	"notebook-line-art",
	"japanese-quiet-minimal",
	"healing-backlight-nature",
] as const satisfies readonly CoverVisualStyle[];

export const HANDCRAFTED_COVER_VISUAL_STYLES = [
	"gouache",
	"oil-painting",
	"luminous-anime-background",
	"architectural-pen-sketch",
	"paper-cut-storybook",
	"seasonal-nature",
	"tranquil-outdoors",
	"elegant-semireal",
	"fantasy-storybook",
	"luminous-youth-anime",
	"miniature-diorama",
	"classic-adventure-novel",
	"limited-color-line-art",
] as const satisfies readonly CoverVisualStyle[];
