import type { ArtworkDefinition } from "../../../theme/artwork/types";

/** chalk original raster works; draft pending review. */
export const ARTWORK_MANIFEST: readonly ArtworkDefinition[] = [
	{
		id: "chalk-mountain-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/chalk/mountain-hero.webp",
		format: "webp",
		width: 1536,
		height: 1024,
		aspect: 1.5,
		touchId: "chalk",
		subjectId: "mountain",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 26,
		maxPrintWidthMm: 128,
		originalityGroupId: "chalk-mountain",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of broad broken strokes and powder marks on a dark ground; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "chalk-sea-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/chalk/sea-hero.webp",
		format: "webp",
		width: 1536,
		height: 1024,
		aspect: 1.5,
		touchId: "chalk",
		subjectId: "sea",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 26,
		maxPrintWidthMm: 128,
		originalityGroupId: "chalk-sea",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of broad broken strokes and powder marks on a dark ground; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "chalk-street-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/chalk/street-hero.webp",
		format: "webp",
		width: 1536,
		height: 1024,
		aspect: 1.5,
		touchId: "chalk",
		subjectId: "street",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 26,
		maxPrintWidthMm: 128,
		originalityGroupId: "chalk-street",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of broad broken strokes and powder marks on a dark ground; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "chalk-machiya-grid-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/chalk/machiya-grid-hero.webp",
		format: "webp",
		width: 1536,
		height: 1024,
		aspect: 1.5,
		touchId: "chalk",
		subjectId: "machiya-grid",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 26,
		maxPrintWidthMm: 128,
		originalityGroupId: "chalk-machiya-grid",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of broad broken strokes and powder marks on a dark ground; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "chalk-urban-window-railway-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/chalk/urban-window-railway-hero.webp",
		format: "webp",
		width: 1536,
		height: 1024,
		aspect: 1.5,
		touchId: "chalk",
		subjectId: "urban-window-railway",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 26,
		maxPrintWidthMm: 128,
		originalityGroupId: "chalk-urban-window-railway",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of broad broken strokes and powder marks on a dark ground; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "chalk-roof-arch-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/chalk/roof-arch-hero.webp",
		format: "webp",
		width: 1536,
		height: 1024,
		aspect: 1.5,
		touchId: "chalk",
		subjectId: "roof-arch",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 26,
		maxPrintWidthMm: 128,
		originalityGroupId: "chalk-roof-arch",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of broad broken strokes and powder marks on a dark ground; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "chalk-train-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/chalk/train-medium.webp",
		format: "webp",
		width: 640,
		height: 640,
		aspect: 1.0,
		touchId: "chalk",
		subjectId: "train",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "chalk-train",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of broad broken strokes and powder marks on a dark ground; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "chalk-airplane-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/chalk/airplane-medium.webp",
		format: "webp",
		width: 640,
		height: 640,
		aspect: 1.0,
		touchId: "chalk",
		subjectId: "airplane",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "chalk-airplane",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of broad broken strokes and powder marks on a dark ground; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "chalk-car-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/chalk/car-medium.webp",
		format: "webp",
		width: 640,
		height: 640,
		aspect: 1.0,
		touchId: "chalk",
		subjectId: "car",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "chalk-car",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of broad broken strokes and powder marks on a dark ground; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "chalk-bag-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/chalk/bag-medium.webp",
		format: "webp",
		width: 640,
		height: 640,
		aspect: 1.0,
		touchId: "chalk",
		subjectId: "bag",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "chalk-bag",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of broad broken strokes and powder marks on a dark ground; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "chalk-tableware-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/chalk/tableware-medium.webp",
		format: "webp",
		width: 640,
		height: 640,
		aspect: 1.0,
		touchId: "chalk",
		subjectId: "tableware",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "chalk-tableware",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of broad broken strokes and powder marks on a dark ground; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "chalk-leaf-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/chalk/leaf-medium.webp",
		format: "webp",
		width: 640,
		height: 640,
		aspect: 1.0,
		touchId: "chalk",
		subjectId: "leaf",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "chalk-leaf",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of broad broken strokes and powder marks on a dark ground; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "chalk-flower-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/chalk/flower-medium.webp",
		format: "webp",
		width: 640,
		height: 640,
		aspect: 1.0,
		touchId: "chalk",
		subjectId: "flower",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "chalk-flower",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of broad broken strokes and powder marks on a dark ground; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "chalk-shell-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/chalk/shell-medium.webp",
		format: "webp",
		width: 640,
		height: 640,
		aspect: 1.0,
		touchId: "chalk",
		subjectId: "shell",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "chalk-shell",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of broad broken strokes and powder marks on a dark ground; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "chalk-photo-frame-frame-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/chalk/photo-frame-frame.webp",
		format: "webp",
		width: 1536,
		height: 1152,
		aspect: 1.333333,
		touchId: "chalk",
		subjectId: "photo-frame",
		role: "frame",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "chalk-photo-frame",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of broad broken strokes and powder marks on a dark ground; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "chalk-heading-band-heading-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/chalk/heading-band-heading.webp",
		format: "webp",
		width: 1536,
		height: 192,
		aspect: 8.0,
		touchId: "chalk",
		subjectId: "heading-band",
		role: "heading",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 32,
		maxPrintWidthMm: 128,
		originalityGroupId: "chalk-heading-band",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of broad broken strokes and powder marks on a dark ground; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "chalk-sticky-note-tab-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/chalk/sticky-note-tab.webp",
		format: "webp",
		width: 1536,
		height: 512,
		aspect: 3.0,
		touchId: "chalk",
		subjectId: "sticky-note",
		role: "tab",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "chalk-sticky-note",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of broad broken strokes and powder marks on a dark ground; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "chalk-ticket-label-label-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/chalk/ticket-label-label.webp",
		format: "webp",
		width: 1536,
		height: 768,
		aspect: 2.0,
		touchId: "chalk",
		subjectId: "ticket-label",
		role: "label",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 128,
		originalityGroupId: "chalk-ticket-label",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of broad broken strokes and powder marks on a dark ground; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "chalk-measurement-rule-rule-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/chalk/measurement-rule-rule.webp",
		format: "webp",
		width: 1536,
		height: 48,
		aspect: 32.0,
		touchId: "chalk",
		subjectId: "measurement-rule",
		role: "rule",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 28,
		maxPrintWidthMm: 128,
		originalityGroupId: "chalk-measurement-rule",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of broad broken strokes and powder marks on a dark ground; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "chalk-grid-panel-panel-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/chalk/grid-panel-panel.webp",
		format: "webp",
		width: 2000,
		height: 1500,
		aspect: 1.333333,
		touchId: "chalk",
		subjectId: "grid-panel",
		role: "panel",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "chalk-grid-panel",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of broad broken strokes and powder marks on a dark ground; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
		views: [{ id: "film", x: 200, y: 150, width: 1600, height: 1200 }],
	},
	{
		id: "chalk-straight-arrow-straight-arrow-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/chalk/straight-arrow-straight-arrow.webp",
		format: "webp",
		width: 900,
		height: 300,
		aspect: 3.0,
		touchId: "chalk",
		subjectId: "straight-arrow",
		role: "straight-arrow",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 30,
		originalityGroupId: "chalk-straight-arrow",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of broad broken strokes and powder marks on a dark ground; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "chalk-turn-arrow-turn-arrow-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/chalk/turn-arrow-turn-arrow.webp",
		format: "webp",
		width: 900,
		height: 300,
		aspect: 3.0,
		touchId: "chalk",
		subjectId: "turn-arrow",
		role: "turn-arrow",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 30,
		originalityGroupId: "chalk-turn-arrow",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of broad broken strokes and powder marks on a dark ground; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "chalk-route-route-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/chalk/route-route.webp",
		format: "webp",
		width: 600,
		height: 1200,
		aspect: 0.5,
		touchId: "chalk",
		subjectId: "route",
		role: "route",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 14,
		maxPrintWidthMm: 30,
		originalityGroupId: "chalk-route",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of broad broken strokes and powder marks on a dark ground; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
	},
	{
		id: "chalk-season-pattern-season-pattern-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/chalk/season-pattern-season-pattern.webp",
		format: "webp",
		width: 1000,
		height: 1000,
		aspect: 1.0,
		touchId: "chalk",
		subjectId: "season-pattern",
		role: "season-pattern",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 36,
		maxPrintWidthMm: 40,
		originalityGroupId: "chalk-season-pattern",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Deterministic Python composition of broad broken strokes and powder marks on a dark ground; encoded to WebP with libwebp.",
			licenseEvidence:
				"Original internal raster artwork authored for this repository; no external source material.",
		},
		reviewId: null,
		hasAlpha: false,
		views: [
			{ id: "spring", x: 0, y: 0, width: 500, height: 500 },
			{ id: "summer", x: 500, y: 0, width: 500, height: 500 },
			{ id: "autumn", x: 0, y: 500, width: 500, height: 500 },
			{ id: "winter", x: 500, y: 500, width: 500, height: 500 },
		],
	},
];
