import type { ArtworkDefinition } from "../../../theme/artwork/types";

/** cut-paper originals; draft until visual review. */
export const ARTWORK_MANIFEST: readonly ArtworkDefinition[] = [
	{
		id: "cut-paper-airplane-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/cut-paper/airplane-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "cut-paper",
		subjectId: "airplane",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "cut-paper-airplane",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Layered cut-paper forms with offset paper shadows, irregular edges and separate matte planes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:cut-paper-airplane-medium-r1:v1:review-20260925",
	},
	{
		id: "cut-paper-bag-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/cut-paper/bag-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "cut-paper",
		subjectId: "bag",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "cut-paper-bag",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Layered cut-paper forms with offset paper shadows, irregular edges and separate matte planes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:cut-paper-bag-medium-r1:v1:review-20260925",
	},
	{
		id: "cut-paper-car-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/cut-paper/car-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "cut-paper",
		subjectId: "car",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "cut-paper-car",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Layered cut-paper forms with offset paper shadows, irregular edges and separate matte planes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:cut-paper-car-medium-r1:v1:review-20260925",
	},
	{
		id: "cut-paper-flower-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/cut-paper/flower-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "cut-paper",
		subjectId: "flower",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "cut-paper-flower",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Layered cut-paper forms with offset paper shadows, irregular edges and separate matte planes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:cut-paper-flower-medium-r1:v1:review-20260925",
	},
	{
		id: "cut-paper-grid-panel-panel-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/cut-paper/grid-panel-panel.svg",
		format: "svg",
		width: 320,
		height: 240,
		aspect: 1.333333,
		touchId: "cut-paper",
		subjectId: "grid-panel",
		role: "panel",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 18,
		maxPrintWidthMm: 128,
		originalityGroupId: "cut-paper-grid-panel",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Layered cut-paper forms with offset paper shadows, irregular edges and separate matte planes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:cut-paper-grid-panel-panel-r1:v1:review-20260925",
	},
	{
		id: "cut-paper-heading-band-heading-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/cut-paper/heading-band-heading.svg",
		format: "svg",
		width: 320,
		height: 40,
		aspect: 8.0,
		touchId: "cut-paper",
		subjectId: "heading-band",
		role: "heading",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 32,
		maxPrintWidthMm: 128,
		originalityGroupId: "cut-paper-heading-band",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Layered cut-paper forms with offset paper shadows, irregular edges and separate matte planes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:cut-paper-heading-band-heading-r1:v1:review-20260925",
	},
	{
		id: "cut-paper-leaf-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/cut-paper/leaf-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "cut-paper",
		subjectId: "leaf",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "cut-paper-leaf",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Layered cut-paper forms with offset paper shadows, irregular edges and separate matte planes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:cut-paper-leaf-medium-r1:v1:review-20260925",
	},
	{
		id: "cut-paper-machiya-grid-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/cut-paper/machiya-grid-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "cut-paper",
		subjectId: "machiya-grid",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "cut-paper-machiya-grid",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Layered cut-paper forms with offset paper shadows, irregular edges and separate matte planes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:cut-paper-machiya-grid-hero-r1:v1:review-20260925",
	},
	{
		id: "cut-paper-measurement-rule-rule-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/cut-paper/measurement-rule-rule.svg",
		format: "svg",
		width: 320,
		height: 10,
		aspect: 32.0,
		touchId: "cut-paper",
		subjectId: "measurement-rule",
		role: "rule",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 24,
		maxPrintWidthMm: 128,
		originalityGroupId: "cut-paper-measurement-rule",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Layered cut-paper forms with offset paper shadows, irregular edges and separate matte planes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:cut-paper-measurement-rule-rule-r1:v1:review-20260925",
	},
	{
		id: "cut-paper-mountain-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/cut-paper/mountain-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "cut-paper",
		subjectId: "mountain",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "cut-paper-mountain",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Layered cut-paper forms with offset paper shadows, irregular edges and separate matte planes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:cut-paper-mountain-hero-r1:v1:review-20260925",
	},
	{
		id: "cut-paper-photo-frame-frame-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/cut-paper/photo-frame-frame.svg",
		format: "svg",
		width: 320,
		height: 240,
		aspect: 1.333333,
		touchId: "cut-paper",
		subjectId: "photo-frame",
		role: "frame",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 18,
		maxPrintWidthMm: 128,
		originalityGroupId: "cut-paper-photo-frame",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Layered cut-paper forms with offset paper shadows, irregular edges and separate matte planes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:cut-paper-photo-frame-frame-r1:v1:review-20260925",
	},
	{
		id: "cut-paper-roof-arch-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/cut-paper/roof-arch-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "cut-paper",
		subjectId: "roof-arch",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "cut-paper-roof-arch",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Layered cut-paper forms with offset paper shadows, irregular edges and separate matte planes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:cut-paper-roof-arch-hero-r1:v1:review-20260925",
	},
	{
		id: "cut-paper-route-route-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/cut-paper/route-route.svg",
		format: "svg",
		width: 120,
		height: 240,
		aspect: 0.5,
		touchId: "cut-paper",
		subjectId: "route",
		role: "route",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 14,
		maxPrintWidthMm: 30,
		originalityGroupId: "cut-paper-route",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Layered cut-paper forms with offset paper shadows, irregular edges and separate matte planes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:cut-paper-route-route-r1:v1:review-20260925",
	},
	{
		id: "cut-paper-sea-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/cut-paper/sea-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "cut-paper",
		subjectId: "sea",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "cut-paper-sea",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Layered cut-paper forms with offset paper shadows, irregular edges and separate matte planes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:cut-paper-sea-hero-r1:v1:review-20260925",
	},
	{
		id: "cut-paper-season-pattern-season-pattern-r1",
		revision: 1,
		sourcePath:
			"../../assets/artwork/cut-paper/season-pattern-season-pattern.svg",
		format: "svg",
		width: 1000,
		height: 1000,
		aspect: 1.0,
		touchId: "cut-paper",
		subjectId: "season-pattern",
		role: "season-pattern",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 30,
		maxPrintWidthMm: 40,
		originalityGroupId: "cut-paper-season-pattern",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Layered cut-paper forms with offset paper shadows, irregular edges and separate matte planes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId:
			"artwork:cut-paper-season-pattern-season-pattern-r1:v1:review-20260925",
		views: [
			{ id: "spring", x: 0, y: 0, width: 500, height: 500 },
			{ id: "summer", x: 500, y: 0, width: 500, height: 500 },
			{ id: "autumn", x: 0, y: 500, width: 500, height: 500 },
			{ id: "winter", x: 500, y: 500, width: 500, height: 500 },
		],
	},
	{
		id: "cut-paper-shell-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/cut-paper/shell-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "cut-paper",
		subjectId: "shell",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "cut-paper-shell",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Layered cut-paper forms with offset paper shadows, irregular edges and separate matte planes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:cut-paper-shell-medium-r1:v1:review-20260925",
	},
	{
		id: "cut-paper-sticky-note-tab-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/cut-paper/sticky-note-tab.svg",
		format: "svg",
		width: 300,
		height: 100,
		aspect: 3.0,
		touchId: "cut-paper",
		subjectId: "sticky-note",
		role: "tab",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 20,
		maxPrintWidthMm: 128,
		originalityGroupId: "cut-paper-sticky-note",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Layered cut-paper forms with offset paper shadows, irregular edges and separate matte planes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:cut-paper-sticky-note-tab-r1:v1:review-20260925",
	},
	{
		id: "cut-paper-straight-arrow-straight-arrow-r1",
		revision: 1,
		sourcePath:
			"../../assets/artwork/cut-paper/straight-arrow-straight-arrow.svg",
		format: "svg",
		width: 300,
		height: 100,
		aspect: 3.0,
		touchId: "cut-paper",
		subjectId: "straight-arrow",
		role: "straight-arrow",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 30,
		originalityGroupId: "cut-paper-straight-arrow",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Layered cut-paper forms with offset paper shadows, irregular edges and separate matte planes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId:
			"artwork:cut-paper-straight-arrow-straight-arrow-r1:v1:review-20260925",
	},
	{
		id: "cut-paper-street-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/cut-paper/street-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "cut-paper",
		subjectId: "street",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "cut-paper-street",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Layered cut-paper forms with offset paper shadows, irregular edges and separate matte planes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:cut-paper-street-hero-r1:v1:review-20260925",
	},
	{
		id: "cut-paper-tableware-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/cut-paper/tableware-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "cut-paper",
		subjectId: "tableware",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "cut-paper-tableware",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Layered cut-paper forms with offset paper shadows, irregular edges and separate matte planes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:cut-paper-tableware-medium-r1:v1:review-20260925",
	},
	{
		id: "cut-paper-ticket-label-label-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/cut-paper/ticket-label-label.svg",
		format: "svg",
		width: 200,
		height: 100,
		aspect: 2.0,
		touchId: "cut-paper",
		subjectId: "ticket-label",
		role: "label",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 14,
		maxPrintWidthMm: 128,
		originalityGroupId: "cut-paper-ticket-label",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Layered cut-paper forms with offset paper shadows, irregular edges and separate matte planes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:cut-paper-ticket-label-label-r1:v1:review-20260925",
	},
	{
		id: "cut-paper-train-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/cut-paper/train-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "cut-paper",
		subjectId: "train",
		role: "medium",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "cut-paper-train",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Layered cut-paper forms with offset paper shadows, irregular edges and separate matte planes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:cut-paper-train-medium-r1:v1:review-20260925",
	},
	{
		id: "cut-paper-turn-arrow-turn-arrow-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/cut-paper/turn-arrow-turn-arrow.svg",
		format: "svg",
		width: 300,
		height: 100,
		aspect: 3.0,
		touchId: "cut-paper",
		subjectId: "turn-arrow",
		role: "turn-arrow",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 30,
		originalityGroupId: "cut-paper-turn-arrow",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Layered cut-paper forms with offset paper shadows, irregular edges and separate matte planes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: "artwork:cut-paper-turn-arrow-turn-arrow-r1:v1:review-20260925",
	},
	{
		id: "cut-paper-urban-window-railway-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/cut-paper/urban-window-railway-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "cut-paper",
		subjectId: "urban-window-railway",
		role: "hero",
		recolor: "none",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "cut-paper-urban-window-railway",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Layered cut-paper forms with offset paper shadows, irregular edges and separate matte planes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId:
			"artwork:cut-paper-urban-window-railway-hero-r1:v1:review-20260925",
	},
];
