on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@1f8e202ffddf94def7f42f6fa3a482e821489f9c # 2026.07.10.1

      - name: install golang-migrate
        run: brew install golang-migrate

      - name: Set up mise
        uses: jdx/mise-action@v4
        with:
          install: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12

      - name: Run tests
        run: go test -v ./...
