import type { ArtworkDefinition } from "../../../theme/artwork/types";

/** pencil originals; draft until visual review. */
export const ARTWORK_MANIFEST: readonly ArtworkDefinition[] = [
	{
		id: "pencil-airplane-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pencil/airplane-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "pencil",
		subjectId: "airplane",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "pencil-airplane",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original pencil drawing with varied pressure outlines, hand-placed exploratory construction accents, and graphite hatching.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "pencil-bag-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pencil/bag-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "pencil",
		subjectId: "bag",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "pencil-bag",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original pencil drawing with varied pressure outlines, hand-placed exploratory construction accents, and graphite hatching.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "pencil-car-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pencil/car-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "pencil",
		subjectId: "car",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "pencil-car",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original pencil drawing with varied pressure outlines, hand-placed exploratory construction accents, and graphite hatching.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "pencil-flower-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pencil/flower-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "pencil",
		subjectId: "flower",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "pencil-flower",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original pencil drawing with varied pressure outlines, hand-placed exploratory construction accents, and graphite hatching.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "pencil-grid-panel-panel-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pencil/grid-panel-panel.svg",
		format: "svg",
		width: 320,
		height: 240,
		aspect: 1.333333,
		touchId: "pencil",
		subjectId: "grid-panel",
		role: "panel",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 18,
		maxPrintWidthMm: 128,
		originalityGroupId: "pencil-grid-panel",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original pencil drawing with varied pressure outlines, hand-placed exploratory construction accents, and graphite hatching.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "pencil-heading-band-heading-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pencil/heading-band-heading.svg",
		format: "svg",
		width: 320,
		height: 40,
		aspect: 8.0,
		touchId: "pencil",
		subjectId: "heading-band",
		role: "heading",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 32,
		maxPrintWidthMm: 128,
		originalityGroupId: "pencil-heading-band",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original pencil drawing with varied pressure outlines, hand-placed exploratory construction accents, and graphite hatching.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "pencil-leaf-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pencil/leaf-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "pencil",
		subjectId: "leaf",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "pencil-leaf",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original pencil drawing with varied pressure outlines, hand-placed exploratory construction accents, and graphite hatching.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "pencil-machiya-grid-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pencil/machiya-grid-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "pencil",
		subjectId: "machiya-grid",
		role: "hero",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "pencil-machiya-grid",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Hand-composed subject-specific vector geometry with exploratory offset contours and light construction strokes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "pencil-measurement-rule-rule-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pencil/measurement-rule-rule.svg",
		format: "svg",
		width: 320,
		height: 10,
		aspect: 32.0,
		touchId: "pencil",
		subjectId: "measurement-rule",
		role: "rule",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 24,
		maxPrintWidthMm: 128,
		originalityGroupId: "pencil-measurement-rule",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original pencil drawing with varied pressure outlines, hand-placed exploratory construction accents, and graphite hatching.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "pencil-mountain-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pencil/mountain-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "pencil",
		subjectId: "mountain",
		role: "hero",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "pencil-mountain",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Hand-composed subject-specific vector geometry with exploratory offset contours and light construction strokes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "pencil-photo-frame-frame-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pencil/photo-frame-frame.svg",
		format: "svg",
		width: 320,
		height: 240,
		aspect: 1.333333,
		touchId: "pencil",
		subjectId: "photo-frame",
		role: "frame",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 18,
		maxPrintWidthMm: 128,
		originalityGroupId: "pencil-photo-frame",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original pencil drawing with varied pressure outlines, hand-placed exploratory construction accents, and graphite hatching.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "pencil-roof-arch-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pencil/roof-arch-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "pencil",
		subjectId: "roof-arch",
		role: "hero",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "pencil-roof-arch",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Hand-composed subject-specific vector geometry with exploratory offset contours and light construction strokes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "pencil-route-route-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pencil/route-route.svg",
		format: "svg",
		width: 120,
		height: 240,
		aspect: 0.5,
		touchId: "pencil",
		subjectId: "route",
		role: "route",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 14,
		maxPrintWidthMm: 30,
		originalityGroupId: "pencil-route",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original pencil drawing with varied pressure outlines, hand-placed exploratory construction accents, and graphite hatching.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "pencil-sea-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pencil/sea-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "pencil",
		subjectId: "sea",
		role: "hero",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "pencil-sea",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Hand-composed subject-specific vector geometry with exploratory offset contours and light construction strokes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "pencil-season-pattern-season-pattern-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pencil/season-pattern-season-pattern.svg",
		format: "svg",
		width: 1000,
		height: 1000,
		aspect: 1.0,
		touchId: "pencil",
		subjectId: "season-pattern",
		role: "season-pattern",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 30,
		maxPrintWidthMm: 40,
		originalityGroupId: "pencil-season-pattern",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original pencil drawing with varied pressure outlines, hand-placed exploratory construction accents, and graphite hatching.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
		views: [
			{ id: "spring", x: 0, y: 0, width: 500, height: 500 },
			{ id: "summer", x: 500, y: 0, width: 500, height: 500 },
			{ id: "autumn", x: 0, y: 500, width: 500, height: 500 },
			{ id: "winter", x: 500, y: 500, width: 500, height: 500 },
		],
	},
	{
		id: "pencil-shell-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pencil/shell-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "pencil",
		subjectId: "shell",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "pencil-shell",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original pencil drawing with varied pressure outlines, hand-placed exploratory construction accents, and graphite hatching.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "pencil-sticky-note-tab-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pencil/sticky-note-tab.svg",
		format: "svg",
		width: 300,
		height: 100,
		aspect: 3.0,
		touchId: "pencil",
		subjectId: "sticky-note",
		role: "tab",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 20,
		maxPrintWidthMm: 128,
		originalityGroupId: "pencil-sticky-note",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original pencil drawing with varied pressure outlines, hand-placed exploratory construction accents, and graphite hatching.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "pencil-straight-arrow-straight-arrow-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pencil/straight-arrow-straight-arrow.svg",
		format: "svg",
		width: 300,
		height: 100,
		aspect: 3.0,
		touchId: "pencil",
		subjectId: "straight-arrow",
		role: "straight-arrow",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 30,
		originalityGroupId: "pencil-straight-arrow",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original pencil drawing with varied pressure outlines, hand-placed exploratory construction accents, and graphite hatching.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "pencil-street-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pencil/street-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "pencil",
		subjectId: "street",
		role: "hero",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "pencil-street",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Hand-composed subject-specific vector geometry with exploratory offset contours and light construction strokes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "pencil-tableware-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pencil/tableware-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "pencil",
		subjectId: "tableware",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "pencil-tableware",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original pencil drawing with varied pressure outlines, hand-placed exploratory construction accents, and graphite hatching.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "pencil-ticket-label-label-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pencil/ticket-label-label.svg",
		format: "svg",
		width: 200,
		height: 100,
		aspect: 2.0,
		touchId: "pencil",
		subjectId: "ticket-label",
		role: "label",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 14,
		maxPrintWidthMm: 128,
		originalityGroupId: "pencil-ticket-label",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original pencil drawing with varied pressure outlines, hand-placed exploratory construction accents, and graphite hatching.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "pencil-train-medium-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pencil/train-medium.svg",
		format: "svg",
		width: 240,
		height: 240,
		aspect: 1.0,
		touchId: "pencil",
		subjectId: "train",
		role: "medium",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 42,
		originalityGroupId: "pencil-train",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original pencil drawing with varied pressure outlines, hand-placed exploratory construction accents, and graphite hatching.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "pencil-turn-arrow-turn-arrow-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pencil/turn-arrow-turn-arrow.svg",
		format: "svg",
		width: 300,
		height: 100,
		aspect: 3.0,
		touchId: "pencil",
		subjectId: "turn-arrow",
		role: "turn-arrow",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 16,
		maxPrintWidthMm: 30,
		originalityGroupId: "pencil-turn-arrow",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Original pencil drawing with varied pressure outlines, hand-placed exploratory construction accents, and graphite hatching.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
	{
		id: "pencil-urban-window-railway-hero-r1",
		revision: 1,
		sourcePath: "../../assets/artwork/pencil/urban-window-railway-hero.svg",
		format: "svg",
		width: 360,
		height: 240,
		aspect: 1.5,
		touchId: "pencil",
		subjectId: "urban-window-railway",
		role: "hero",
		recolor: "mask",
		safeInset: { top: 0.06, right: 0.06, bottom: 0.06, left: 0.06 },
		minPrintWidthMm: 22,
		maxPrintWidthMm: 128,
		originalityGroupId: "pencil-urban-window-railway",
		provenance: {
			creator: "Cacao artwork studio",
			method:
				"Hand-composed subject-specific vector geometry with exploratory offset contours and light construction strokes.",
			licenseEvidence:
				"Original internal SVG artwork; no external source material used.",
		},
		reviewId: null,
	},
];
